package/endpoint/dataset/metadata/elasticsearch/transform/current-default.json

We can now successfully deploy an 8.0 cloud instance which will stand up Ingest and install the transform.  Reverting this change so that we don't push this to the registry.
More info: https://github.com/elastic/kibana/issues/77133#issuecomment-692792691

add the transform file back

---

README.md

Since elastic/package-storage/pull/116, the production packages have been moved to a `production` folder, so this link isn't valid anymore.

Fix remote endpoint branch

---

Pipfile
Pipfile.lock
scripts/release_manager/main.py

This PR improves the package release script by:
- Calculating a xxhash (using xxhash for speed) of the endpoint package directory to include in the PR
- This will help with simple verification when using the `elastic-package promote` script to ensure that the package is the same as it is promoted to a new environment
- Adding functionality for creating the new release branch (7.10, 7.11, etc) after releasing a package
https://github.com/elastic/package-storage/pull/476
```
Is this a dev or prod release? (dev, prod) [dev]: prod
Current package version: 0.17.0-dev.0
Which upstream branch should we release from? (7.10, 7.9, master, master_test) [master]: master_test
Preparing for a release, removing the build number
Version: 0.17.0
Tagging endpoint version: v0.17.0
Copying package to: …
```

Improve release process

---

scripts/release_manager/main.py

This PR will update the `.backportrc.json` file during a release off of the `master` branch (since backporting only applies from master to other release branches).

Update .backportrc.json during release

---

custom_subsets/elastic_endpoint/file/file.yaml
generated/file/ecs/ecs_flat.yml
generated/file/ecs/subset/file/ecs_flat.yml
generated/file/elasticsearch/7/template.json
package/endpoint/data_stream/file/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/file/file.yaml

Backports the following commits to 7.10:
- Add file.extension and process.args_count to file events mapping (#97)

[7.10] Add file.extension and process.args_count to file events mapping (#97)

---

package/endpoint/manifest.yml

This isn't super necessary but since we changed the metadata schema and a lot of testing already went into 7.10 we'll keep the changes for 7.11 only.

Bumping kibana condition to 7.11

---

custom_subsets/elastic_endpoint/library/library.yaml
generated/library/ecs/ecs_flat.yml
generated/library/ecs/subset/library/ecs_flat.yml
generated/library/elasticsearch/7/template.json
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/library/library.yaml

Backports the following commits to 7.10:
- Adding missing dll fields (#109)

[7.10] Adding missing dll fields (#109)

---

Makefile
generated/alerts/elasticsearch/7/template.json
generated/file/elasticsearch/7/template.json
generated/library/elasticsearch/7/template.json
generated/metadata/elasticsearch/7/template.json
generated/metrics/elasticsearch/7/template.json
generated/network/elasticsearch/7/template.json
generated/policy/elasticsearch/7/template.json
generated/process/elasticsearch/7/template.json
generated/registry/elasticsearch/7/template.json
generated/security/elasticsearch/7/template.json

Pinning the ECS repo to `1.7.0` so the build will succeed and it gets us off the bleeding edge of master which is currently failing. This is temporary, in a follow up PR I'm going to bump the ECS schema version we use internally so we can be on `1.7.0` for everything.
NOTE: You'll need to `make clean` after this is merged.

Pinning ECS version to 1.7.0 a working version for the build

---

Makefile
generated/alerts/elasticsearch/7/template.json
generated/file/elasticsearch/7/template.json
generated/library/elasticsearch/7/template.json
generated/metadata/elasticsearch/7/template.json
generated/metrics/elasticsearch/7/template.json
generated/network/elasticsearch/7/template.json
generated/policy/elasticsearch/7/template.json
generated/process/elasticsearch/7/template.json
generated/registry/elasticsearch/7/template.json
generated/security/elasticsearch/7/template.json

Backports the following commits to 7.10:
- Pinning ecs version to a working version for the build (#114)

[7.10] Pinning ecs version to a working version for the build (#114)

---

package/endpoint/elasticsearch/transform/metadata_current/default.json

Alters the Metadata transform query to [not include documents older than 90 days](https://github.com/elastic/security-team/issues/698)
Functional proof:
https://user-images.githubusercontent.com/315796/104203128-ca3eaf80-53f9-11eb-95ee-a34273386158.mp4

metadata transform: only grab documents newer than 90d

---

Makefile

Skipping this temporarily while we try to get the package spec updated here: https://github.com/elastic/elastic-package/pull/216

Skipping linting for now until it is fixed

---

custom_schemas/custom_file.yml
custom_subsets/elastic_endpoint/file/file.yaml
generated/file/ecs/ecs_flat.yml
generated/file/ecs/subset/file/ecs_flat.yml
generated/file/elasticsearch/7/template.json
package/endpoint/data_stream/file/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/file/file.yaml

The first time around, I was planning to include both header and trailer bytes.  The trailer bytes ended up being unnecessary.  Changing to header_trailer_data --> header_data to more accurately describe the field.

Changing file header bytes name

---

package/endpoint/elasticsearch/index_template/metrics-metadata-current.json
package/endpoint/elasticsearch/transform/metadata_current/default.json

Adjust the transform so that it will also search for indices that may have something other than the `default` namespace.
See this bug:
https://github.com/elastic/kibana/issues/86237

expand transform index search to account for namespaces

---

custom_subsets/elastic_endpoint/library/library.yaml
generated/library/ecs/ecs_flat.yml
generated/library/ecs/subset/library/ecs_flat.yml
generated/library/elasticsearch/7/template.json
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/library/library.yaml

Include `dll.code_signatures` in the mapping for dll events.
Address issue found here: https://github.com/elastic/detection-rules/pull/819#discussion_r565525356

Mapping dll.code_sig

---

package/endpoint/elasticsearch/index_template/metrics-metadata-current.json
package/endpoint/elasticsearch/transform/metadata_current/default.json

the ML team added a native "latest" function of transforms, designed after our use case. This migrates our transform to start using it.
This involves a destination index schema change, Where the previous schema was:
```
{
"agent":{ "id": "XYZ" },
"HostDetails": { <sourcedoc> }
}
```
and agent.id is available as a field inside that sourcedoc. New schema becomes:
```
{ <sourcedoc> }
```
where `agent.id` remains available at the same place, now.
Kibana PR to sync up with the schema change: https://github.com/elastic/kibana/pull/88012

Change endpoint metadata transform to use "latest" operator

---

.gitattributes
custom_schemas/custom_dll.yml
custom_subsets/elastic_endpoint/library/library.yaml
generated/library/ecs/ecs_flat.yml
generated/library/ecs/subset/library/ecs_flat.yml
generated/library/elasticsearch/7/template.json
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/library/library.yaml

Relates to https://github.com/elastic/endpoint-dev/issues/8659
It can be useful to know when certain system DLLs (ntdll, kernel32) have been loaded a second time into any given process.  This can indicate malicious behavior.  These DLLs are normally loaded into each Windows process once at startup, so a "process creation" event generally implies one load of each of these DLLs, and is thus uninteresting and noisy.  Discussions with @joe-desimone led to a decision to only report on the second load of those two DLLs, to reduce noise and data volume.  I've already implemented this in the Endpoint here: https://github.com/elastic/endpoint-dev/pull/8661
This will eventually lead to rules where we say "I want to know about the load of kernel32", but only the second.  We need some way to clearly …

Add DLL load_index

---

custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/process/process.yaml
generated/process/ecs/ecs_flat.yml
generated/process/ecs/subset/process/ecs_flat.yml
generated/process/elasticsearch/7/template.json
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/process/process.yaml

The description of the new field should explain this.  If it doesn't, I should update that instead of explaining it here.

Add defense evasion list to process creation events

---

package/endpoint/manifest.yml

This PR bumps the manifest version for 7.13. I'll backport this to the 7.13 branch once it's merged.

Bumping the manifest version for 7.13

---

package/endpoint/manifest.yml

Backports the following commits to 7.13:
- Bumping the manifest version for 7.13 (#147)

[7.13] Bumping the manifest version for 7.13 (#147)

---

package/endpoint/elasticsearch/transform/metadata_current/default.json

This PR is meant to make the transform that operates on Endpoint metadata faster.  This will improve performance and improve the UX for users since the UI will appear more responsive when using the Endpoint list.
This was tested with a cloud server with ~280k unique Endpoint metadata docs.  There are over a million docs in the metadata source index.  The transform keeps up with the amount of data and properly indexes new Endpoint docs that are streamed.  In addition, when connecting real endpoints, the UI is more responsive since the transform will reflect Endpoint changes more quickly.
Testing methods:
- Continually stream new metadata docs into ES using our generator.  This allows us to easily control the amount of unique Endpoints we stream in and what to expect from the UI.  The …

[Security Solution] Make Endpoint metadata transform delay and frequency fields faster

---

custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/alerts/malware_event.yaml
custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
custom_subsets/elastic_endpoint/alerts/ransomware_event.yaml
custom_subsets/elastic_endpoint/process/process.yaml
generated/alerts/ecs/ecs_flat.yml
generated/alerts/ecs/subset/malware_event/ecs_flat.yml
generated/alerts/ecs/subset/memory_protection_event/ecs_flat.yml
generated/alerts/ecs/subset/ransomware_event/ecs_flat.yml
generated/alerts/elasticsearch/7/template.json
generated/process/ecs/ecs_flat.yml
generated/process/ecs/subset/process/ecs_flat.yml
generated/process/elasticsearch/7/template.json
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/malware_event.yaml
schemas/v1/alerts/memory_protection_event.yaml
schemas/v1/alerts/ransomware_event.yaml
schemas/v1/process/process.yaml

Issue: https://github.com/elastic/endpoint-dev/issues/8759
Windows has a concept of a Protected Process, which has strict code signing requirements and other limitations in order to keep malware out.
By adding process protection level to events and alerts, we can harden allowlist and trustedapp actions for known-problematic processes by adding a PPL requirement.   This rules out a variety of trivial backdoors that would otherwise be a concern.
This may help us avoid performance issues like: https://discuss.elastic.co/t/issues-with-elastic-agent-and-defender/269818
Note: Protection is a property of the process, not its access token.

Add Process protection level to events and alerts

---

package/endpoint/elasticsearch/index_template/metrics-metadata-current.json

Correct the field name in the transform destination mapping (it is `isolation` in the data stream schemas already)

update transform mapping isolated->isolation

---

package/endpoint/manifest.yml

Mark the package as GA, and update the owning team to OLM
Will backport this to `7.14` branch

Take endpoint security out of beta

---

package/endpoint/elasticsearch/transform/metadata_current/default.json

Endpoint (the binary) v7.14 will start sending a new value for its `agent.id`. So upgrading agent+endpoint will result in duplicate hosts from this transform. The `elastic.agent.id` will be the same value across upgrades, and resolves the change as a consistent, single host
This is to handle https://github.com/elastic/kibana/issues/105035

Set transform pivot to elastic.agent.id

---

.bumpversion.cfg
package/endpoint/manifest.yml

Corrected versioning schema:
| branch | stack version | prev pkg ver | new pkg ver | PR |
|-----------|-------------------|------------------|------------------|-----: |
| `7.14`   | 7.14               | 0.20.2          |  1.0.0            |  https://github.com/elastic/package-storage/pull/1956 |
| `7.15`   |  7.15              | 0.21.0          |   1.1.0           | https://github.com/elastic/package-storage/pull/1957 |
| `master` | 7.16             | 0.22.0          | 1.2.0             | this one |

7.16 version should now be 1.2.x

---

package/endpoint/elasticsearch/index_template/metrics-metadata-current.json

This adds `updated_at` as an alias field to `@timestamp` in the mapping for the metadata-latest transform destination index (`metrics-endpoint.metadata_current_default`).
The reasoning here is to match a field name that exists in `.fleet-agents`, the same `updated_at` field which is a timestamp. This will allow a (PR to come) new transform to unite these two with a time-sync field by the same name.
The `updated_at` field *will not* appear in result documents for this transform destination. the `_source` document is unchanged. This just allows _queries_ to also use `updated_at` as a field name to query by. This is otherwise a transparent change.
<details>
<summary>Query</summary>
```sh
echo '{
"query": {
"range": {
"updated_at": {
"gte": "2021-08-01T12:00:00",
"lte": "2021-10-01T12:00:00" …
```

[United Meta] Add updated_at alias to metadata-latest, matching fleet

---

package/endpoint/elasticsearch/index_template/metrics-metadata-united.json
package/endpoint/elasticsearch/transform/metadata_united/default.json

This creates the baseline united transform, with mappings as we currently know them (copy of endpoint-metadata and copy of .fleet-agents nested under `united.endpoint` and `united.agent` respectively).
Screenshot of running transforms after package upgrade:
Screenshot of results (`GET /.metrics-endpoint.metadata_united_default/_search   {"query": {"match_all": {}}}`)

[United Meta] Add united transform, and current mapping

---

.github/PULL_REQUEST_TEMPLATE/Other.md
.github/PULL_REQUEST_TEMPLATE/Schema_change.md
.github/PULL_REQUEST_TEMPLATE/Transform.md

Now, when people create PRs to the package, we have some reminders and requests for info, so we can match up the intent (e.g. use of the new schema field, and sample values) with the change and field type

[Maintenance] Add some pull request templates

---

package/endpoint/data_stream/metadata/manifest.yml
package/endpoint/elasticsearch/index_template/metrics-metadata-current.json
package/endpoint/elasticsearch/index_template/metrics-metadata-united.json
package/endpoint/elasticsearch/transform/metadata_united/default.json

* adds new united metadata transform which joins the .fleet-agents and metrics-endpoint.metadata_current_default indices
* enables index sorting [timestamp, agent.id] on metrics-endpoint.metadata_current_default and metadata ds

add new united metadata transform

---

custom_schemas/custom_token.yml
custom_subsets/elastic_endpoint/process/process.yaml
schemas/v1/process/process.yaml

Add `process.Ext.token.security_attributes`, which contains the names of all the values in the [TokenSecurityAttributes](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-token_information_class) information class.  [Here's](https://github.com/processhacker/processhacker/blob/ac8578d86bbca9924e9cec2c09ec495d44a6f3fd/ProcessHacker/tokprp.c#L3118-L3171) code demonstrating how to collect it.
```json
"process": {
"Ext": {
"token": {
"security_attributes": [
"TSA://ProcUnique",
"LUA://DecHdAutoAp"
]
}
}
}
```

Added security attributes

---

custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
generated/alerts/ecs/ecs_flat.yml
generated/alerts/elasticsearch/7/template.json
package/endpoint/data_stream/alerts/fields/fields.yml
schemas/v1/alerts/memory_protection_event.yaml

Adds additional thread information fields related to call stacks.
This improves our ability to write strong exceptionlist rules.
The additional fields are -
```
process.thread.Ext.call_stack_summary
process.thread.Ext.call_stack_final_user_module.name
process.thread.Ext.call_stack_final_user_module.path
process.thread.Ext.call_stack_final_user_module.hash.sha256
process.thread.Ext.call_stack_final_user_module.code_signature
```

new fields for improved call_stack details

---

package/endpoint/manifest.yml

kibana compat `^8.0.0` -> `^8.1.0` to support kibana main branch which is on 8.1.x now.

bump kibana compat to ^8.1.0

---

custom_schemas/custom_malware_signature.yml
generated/alerts/ecs/ecs_flat.yml
generated/alerts/elasticsearch/7/template.json
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/memory_protection_event.yaml

Changes from `nested` to `keyword`. Looks like the expected values are an array of concrete values (strings, it looks like)
this stems from https://github.com/elastic/endpoint-package/issues/211
```json
"malware_signature": {
"all_names": "Linux.EICAR.Not-a-virus",
"identifier": "production-malware-signature-v1-linux",
"primary": {
"matches": [
"WDVPIVAlQEFQWzRcUFpYNTQoUF4pN0NDKTd9JEVJQ0FSLVNUQU5EQVJELUFOVElWSVJVUy1URVNULUZJTEUhJEgrSCo="
],
},
```
7.16

set malware_signature.primary.matches as unindexed keyword

---

package/endpoint/manifest.yml

This reverts commit 62b3dc42de4b2e9c8558035ea62dfe9e410cb583.
bump to `^8.1.0` was incorrect as it made `8.1.0` to minimum supported version. reverting back to `^8.0.0`.

Revert "bump kibana compat to ^8.1.0 (#213)"

---

package/endpoint/elasticsearch/transform/metadata_current/default.json
package/endpoint/elasticsearch/transform/metadata_united/default.json

Adds `Managed` flag to both transforms, marking them as "system" transforms
8.0.0 (package `1.3` series)

Set both transforms to be "managed" mode

---

Makefile
custom_subsets/elastic_endpoint/network/network.yaml
generated/network/ecs/ecs_flat.yml
generated/network/elasticsearch/7/template.json
package/endpoint/data_stream/network/elasticsearch/ingest_pipeline/default.yml
package/endpoint/data_stream/network/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/network/network.yaml

Adding `asn` and `organization_name` to the network geoip pipeline. This is needed for a machine learning feature.
The added pipelines moves the fields to the appropriate places so that they are ECS compliant:
https://www.elastic.co/guide/en/ecs/1.11/ecs-as.html
specifically `as.number` and `as.organization.name`.
This PR implements similar logic to the zeek package's pipeline: https://github.com/elastic/beats/blob/a1c6774256fe58f711dba0845d094ff5cdff10ee/x-pack/filebeat/module/zeek/connection/ingest/pipeline.yml#L74-L111
8.1
I tested this locally using the following commands in dev tools
To get the database downloaded by Elasticsearch you have to enable it here: https://github.com/elastic/kibana/blob/main/packages/kbn-es/src/cluster.js#L254
```
PUT …
```

Adding asn

---

package/endpoint/manifest.yml

With the addition of a 7.17 stack, let's increment the package to follow.
package `1.2.x` series will continue to serve stack `7.16`.
package `1.3.x` series will target 7.17 stack
which will bump `1.4.x` package series to track kibana `8.0`

Make 1.3 series target 7.17 release

---

package/endpoint/elasticsearch/index_template/metrics-metadata-united.json

Starting in ES 8.0, hidden indices do not just mean start-with-leading-dot. The `index.hidden` setting was added.
This sets our dot-prefixed united metadata index to have `hidden: true`
8.0

Hide .metrics-metadata-united

---

package/endpoint/elasticsearch/index_template/metrics-metadata-united.json

backport of #223 to 8.0 (1.4 package series)

[8.0][backport] hide .metrics-metadata-united (#223)

---

package/endpoint/data_stream/alerts/manifest.yml

Raise the alerts `total_fields` setting, so that Fleet may remove their explicit setting (at 10k, letting it default to 1k).
Original Fleet field removal:
- https://github.com/elastic/kibana/issues/104620
- https://github.com/elastic/kibana/pull/114101
And subsequent reversal when our alerts index was over 1k:
- https://github.com/elastic/kibana/pull/114299
8.0

increase alerts total_fields limit

---

package/endpoint/elasticsearch/index_template/metrics-metadata-current.json
package/endpoint/elasticsearch/index_template/metrics-metadata-united.json

Adding explicit value for keyword_constant types in the latest + united metadata transform destination indices to fix [es deprecation warning for no put mapping permissions](https://github.com/elastic/security-team/issues/2476). Since the value wasn't previously provided, the mapping was being updated when the first document gets indexed causing us to require mapping put permissions for kibana_system.

add endpoint metadata mapping keyword_constant values

---

custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
generated/alerts/ecs/ecs_flat.yml
generated/alerts/elasticsearch/7/template.json
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/memory_protection_event.yaml

`mapped_path` was not initially included in the memory_protection_event subset for `memory_region`. However, this field is required in some scenarios. 
It is currently referenced in the descriptions of other included fields such as `mapped_pe_detected` which is defined as "Whether the file at mapped_path is an executable".
* 8.1

[memory_protection_event] memory_region.mapped_path

---

package/endpoint/elasticsearch/transform/metadata_current/default.json
package/endpoint/elasticsearch/transform/metadata_united/default.json

Reducing `metadata_current` and `metadata_united` transform frequencies down to 1s per outcome from https://github.com/elastic/security-team/issues/2261.

lower current + united transform frequencies to 1s

---

package/endpoint/elasticsearch/index_template/metrics-metadata-current.json

I found this bug while doing some local testing: https://github.com/elastic/kibana/issues/127404
The root cause is that my host VM had a time drift into the future.  I discovered that our `united` transform looks to sync on an `updated_at` field which is contained in the `fleet_agents*` index and in an alias in the `metadata_current` index.
I updated the alias of `updated_at` in the mapping of the `metadata_current` index to point to `event.ingested`.  Previously it was pointing at `@timestamp` which refers to the time on the Host itself.  `event.ingested` should be used because it refers to server time.
It's important to point this at server time because the `updated_at` field is used in this transform: https://github.com/elastic/endpoint-package/blob/master/package/endpoint/elasticsearch …

[Security Solution] Update the alias in this mapping to point to event.ingested

---

custom_subsets/elastic_endpoint/alerts/linux_event_model_event.yaml
custom_subsets/elastic_endpoint/process/linux_event_model_event.yaml
generated/alerts/ecs/ecs_flat.yml
generated/alerts/elasticsearch/7/template.json
generated/process/ecs/ecs_flat.yml
generated/process/elasticsearch/7/template.json
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/linux_event_model_event.yaml
schemas/v1/process/linux_event_model_event.yaml

Small amendment to the previous linux-process-model PR.
8.2

Added missing mapping for process.env_vars

---

custom_subsets/elastic_endpoint/alerts/linux_event_model_event.yaml
custom_subsets/elastic_endpoint/process/linux_event_model_event.yaml
generated/alerts/ecs/ecs_flat.yml
generated/alerts/elasticsearch/7/template.json
generated/process/ecs/ecs_flat.yml
generated/process/elasticsearch/7/template.json
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/linux_event_model_event.yaml
schemas/v1/process/linux_event_model_event.yaml

Due to some consistency issues with the ECS 8.2 release we need to include process.user mapping.
8.2

process.user mapping re-added

---

package/endpoint/elasticsearch/transform/metadata_united/default.json

In Endpoint management dev testing, we noticed that the shorter delays in the united transform were periodically dropping documents when using our endpoint generator dev tool.
When I was running tests which added ~30 Agent and Endpoint docs resulted in the `united` transform, I noticed that documents from our generator dev tool would periodically be dropped.  I believe this has to do with look back in the transform when combining the Agent and Endpoint documents.
After increasing the delay in the `united` transform, all transforms kept up without problems when I left the generator running, adding a total of 2000 Agent and Endpoint docs.
See the Agent/Endpoint counts match below.
`8.2`

[Security Solution] Increase delay of united transform

---

Makefile

Until such time that this package is brought into spec, the linter will fail. The problems have expanded past the changelog entry. For now, `lint` is being removed as a default `make` step so that the package will build without error (when linting is the sole error source).
Linting is being sorted out separately, and will be added to the CI system, so it is likely less necessary to have it as _part_ of the build step, but will be available as `make lint` to test locally, when it is working
This addresses problems like #236

Disable default Lint in make

---

custom_subsets/elastic_endpoint/library/library.yaml
generated/library/ecs/ecs_flat.yml
generated/library/elasticsearch/7/template.json
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/library/library.yaml

Two things happened here:
1. There was a yaml-spacing error in `library` index, so now `process.Ext.code_signature` had its spacing fix, and build files regenerated
2. The build system was not copying over some older changes. No amount of `make` would pick these up. But deleting `alerts/fields/fields.yml` along with `library` and `process` finally picked up these changes.
Further discussion on preventing the second item from missing things is captured in #251 
8.3

Generate catchup

---

scripts/release_manager/main.py

Ignore `_dev` dirs when creating PR to `package-storage` due to new `package-spec` restriction. Attempted to switch to `elastic-package publish` but `package-spec` currently doesn't have `transform` or `index_template` in the spec so we'll need to add those in before we can make this switch ([though there is an open PR to add transform to spec](https://github.com/elastic/package-spec/pull/307)).

ignore _dev dirs for package-storage PR

---

.ci/Jenkinsfile

This sets up auto-publishing from our release branches to package-storage v2.
So now, to publish some changes that need to be backported to package in the`8.2` series, for example:
- make commits and merge to `master` as usual (this then gets auto-published to latest package)
- backport to `8.2` branch similar to the `kibana` repo flow
- when merged into `8.2` branch, the prerelease (`8.2.1-dev.1`) is then auto-published and can be tested
- to production-deploy, a commit that sets the version on `8.2` branch to `v8.2.1` then cuts a full production release.

Add release branches to deploy instructions

---

package/endpoint/manifest.yml

_Presumably_, when this is merged, it will release `8.4.1` package to package-storage **V2**.
I am doing this slightly differently (and manually) to test if v2 storage deploys will work with single merges like this.
Once this is merged, we can deploy to package storage v1 from the commit generated by this merge

8.4.1 release

---

.ci/Jenkinsfile

String-based syntax for parameters of `triggerRemoteJob` doesn't work on latest Jenkins LTS. Migrate to the new map-based syntax.
Issue found in https://github.com/elastic/elastic-package/pull/928, solution evaluated in https://github.com/elastic/elastic-package/pull/929.

Stop using legacy syntax for parameters on triggerRemoteJob

---

package/endpoint/elasticsearch/index_template/metrics-metadata-united.json

Updating united index mapping to include new fields in `.fleet-agents`: https://github.com/elastic/elasticsearch/pull/89599. Left both as `enabled: false` since I don't believe we'll need to be searching on them.
8.5

add new `.fleet-agents` fields to united index

---

doc_templates/endpoint/docs/README.md
package/endpoint/docs/README.md
package/endpoint/manifest.yml

Part of this ticket: https://github.com/elastic/security-team/issues/4759
Update the integration name to Elastic Defend.
Made the package and ran it locally:
No mapping changes in this PR.
8.5

Update integration name to Elastic Defend

---

package/endpoint/elasticsearch/index_template/metrics-metadata-united.json

This PR fixes a bug in the `metadata-united` index pattern.  Before, Fleet would fail to install the Endpoint package citing the `metadata_united` index pattern as invalid.
Before we were using the `enabled` field like this:
```
"last_checkin_message": {
"type": "text",
"enabled": false
},
```
`"enabled"` does not look like it's compatible with `"type": "text"` .  I assumed the intention was to not index the field, so I added `"index:" "false"` to replace `"enabled"`.  After this change, Fleet is able to install the Endpoint package.
`8.5`

[Security Solution] Fix united index template

---

.ci/jobs/defaults.yml
.ci/jobs/endpoint-package-mbp.yml
README.md

Use `fleet-ci`  to scale horizontally the CI.
In order to distribute the load and reduce a single point of failure,
Package v1 won't be migrated to `fleet-ci` as discussed in https://github.com/elastic/package-storage/pull/3714 hence I didn't update the URL in the `README.md`

jjbb: use fleet-ci

---

custom_schemas/custom_group.yml
custom_schemas/custom_user.yml
custom_subsets/elastic_endpoint/process/linux_event_model_event.yaml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/process/sample_event.json
package/endpoint/docs/README.md
schemas/v1/process/linux_event_model_event.yaml

The following fields/mappings:
process.entry_leader.attested_user.id
process.entry_leader.attested_user.name
process.entry_leader.attested_groups.name
```
process.entry_leader.attested_user.id: '123'
process.entry_leader.attested_user.name: 'daniel'
process.entry_leader.attested_groups = [
{ name: 'sudoers' },
{ name: 'docker' }
]
```
```json
"process": {
.....
"entry_leader": {
.....
"attested_user": {
"id": "123",
"name": "userA"
},
"attested_groups": [
{ "name": "groupA" }
]
},
}
```
8.5

[8.5] attested_user and attested_groups added to process.entry_leader

---

custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/process/process.yaml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/process/sample_event.json
package/endpoint/docs/README.md
schemas/v1/process/process.yaml

Schema changes related to https://github.com/elastic/endpoint-dev/pull/11979
8.6.0

Added call_stack_contains_unbacked field

---

custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/alerts/malware_event.yaml
custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
custom_subsets/elastic_endpoint/alerts/ransomware_event.yaml
custom_subsets/elastic_endpoint/process/process.yaml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/process/sample_event.json
package/endpoint/docs/README.md
schemas/v1/alerts/malware_event.yaml
schemas/v1/alerts/memory_protection_event.yaml
schemas/v1/alerts/ransomware_event.yaml
schemas/v1/process/process.yaml

Add session data to Windows process creation events.
See my changes to `package/endpoint/data_stream/process/sample_event.json`
8.6.0

Add session data to Windows process creation events

---

.ci/Jenkinsfile
README.md
scripts/release_manager/main.py

The primary branch for this repo was changed from `master` to `main`. This updates some scripts and CI wherever there was a reference to the old branch name

master -> main

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

Setup `8.6` branch with correct prerelease version tags
The empty changelog entry is annoyingly required for lint passing

prep the 8.6.x dev branch

---

custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/alerts/malware_event.yaml
custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
custom_subsets/elastic_endpoint/alerts/ransomware_event.yaml
custom_subsets/elastic_endpoint/process/process.yaml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/process/sample_event.json
package/endpoint/docs/README.md
schemas/v1/alerts/malware_event.yaml
schemas/v1/alerts/memory_protection_event.yaml
schemas/v1/alerts/ransomware_event.yaml
schemas/v1/process/process.yaml

Rename `process.Ext.session` -> `session_info`.  Restores `process.Ext.session` as a `keyword` field, reverting part of https://github.com/elastic/endpoint-package/pull/309.  @kevinlog raised a concern about potential backwards compatibility.  I don't believe the field was ever used, but I'm opening this so we can be ready to merge it if we decide to do so.
We don't necessarily want to merge this.  It's still up for discussion.
See adjustment to `package/endpoint/data_stream/process/sample_event.json`
8.6.0

Rename `process.Ext.session` -> `session_info` and restore legacy keyword field

---

Makefile
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/file/fields/fields.yml
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/data_stream/metadata/fields/fields.yml
package/endpoint/data_stream/metrics/fields/fields.yml
package/endpoint/data_stream/network/fields/fields.yml
package/endpoint/data_stream/policy/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/process/sample_event.json
package/endpoint/data_stream/registry/fields/fields.yml
package/endpoint/data_stream/security/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/linux_event_model_event.yaml
schemas/v1/alerts/malware_event.yaml
schemas/v1/alerts/memory_protection_event.yaml
schemas/v1/alerts/ransomware_event.yaml
schemas/v1/alerts/rule_detection_event.yaml
schemas/v1/file/file.yaml
schemas/v1/file/unquarantine.yaml
schemas/v1/library/library.yaml
schemas/v1/metadata/metadata.yaml
schemas/v1/metrics/metrics.yaml
schemas/v1/network/network.yaml
schemas/v1/policy/policy.yaml
schemas/v1/process/linux_event_model_event.yaml
schemas/v1/process/process.yaml
schemas/v1/registry/registry.yaml
schemas/v1/security/security.yaml

Update the ECS version that Endpoint pulls in to `8.5.2`.  This is primarily done to get the updated field type for `env_vars`.
```
"env_vars": [
"NICK=test",
"OTHER=why"
],
```
```json
{
"@timestamp": "2022-11-29T20:16:45.9250502Z",
"agent": {
"id": "13146eac-6aa0-4332-86d7-21575ed20003",
"type": "endpoint",
"version": "8.6.0"
},
"data_stream": {
"dataset": "endpoint.events.process",
"namespace": "default",
"type": "logs"
},
"ecs": {
"version": "1.11.0"
},
"elastic": {
"agent": {
"id": "13146eac-6aa0-4332-86d7-21575ed20003"
}
},
"event": {
"action": "end",
"category": [
"process"
],
"created": "2022-11-29T20:16:45.9250502Z",
"dataset": "endpoint.events.process",
"id": "MsIOUUNct/5WrYET+++++lrj",
"kind": "event",
"module": "endpoint",
"sequence": 182036,
"type": [
"end"
] …
```

Update ECS to 8.5.2

---

.ci/Jenkinsfile

This updates the Jenkins file for the `8.6` branch to publish new packages on the `8.6.x` line.  It should publish any incremented `8.6.x` packages merged to the `8.6` branch.

Update 8.6 branch Jenkins file to publish 8.6.x line Endpoint packages

---

custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/process/process.yaml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/process/sample_event.json
package/endpoint/docs/README.md
schemas/v1/process/process.yaml

Add `mitigation_policies` to Windows process creation events.
```
"mitigation_policies": [
"Microsoft only",
"CET dynamic APIs can only be called out of proc",
"CF Guard"
],
```
[Here](https://gist.github.com/Trinity2019/850860a400ec54605300532b2eeed565)'s a sample process event document.
8.7.0

Mitigation policies

---

README.md
docker-compose.yml
package-registry.config.yml

All packages are now pushed to a single place at `https://epr.elastic.co/`.  As a result, use a new environment variable in the registry docker to pull all other packages from the central registry.
In addition, update the README to show how to properly test your in development Endpoint package.

Update `run-registry` command and README

---

custom_schemas/custom_dll.yml
custom_subsets/elastic_endpoint/library/library.yaml
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/data_stream/library/sample_event.json
package/endpoint/docs/README.md
schemas/v1/library/library.yaml

Add DLL sizes.  Protections is interested in this information.
See `package/endpoint/data_stream/library/sample_event.json`
8.7.0

Report DLL Sizes

---

custom_schemas/custom_dll.yml
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/library/library.yaml

When installing the new Endpoint package with the 8.7.0 changes, the addition of a type `u64` is causing the package to fail to install.  This changes this to be `unsigned_long` which is a supported type and can be installed.
The merge that introduced the unsupported type was only applied to the 8.7.0 line, so we just need to fix it here before releasing the new package.  The problem has not been released to production.
PR with the u64 type: https://github.com/elastic/endpoint-package/pull/329
Console error with u64 type:
new installed template with `unsigned_long`
```json
```

Update unsupported u64 type to unsigned_long

---

custom_schemas/custom_api.yml
package/endpoint/data_stream/api/fields/fields.yml
schemas/v1/api/api.yaml

This small PR fixes an error in `custom_schemas/custom_api.yml` where the field  `process.Ext.api.name`  was marked as non-indexable when it should be.
8.7

[Fix] Make `process.Ext.api.name` indexable

---

.ci/Jenkinsfile

This updates the Jenkins file for the `8.7` branch to publish new packages on the `8.7.x` line.  It should publish any incremented `8.6.x` packages merged to the `8.7` branch.

Update 8.7 branch Jenkins file to publish 8.7.x line Endpoint packages

---

package/endpoint/elasticsearch/transform/metadata_current/default.json
package/endpoint/elasticsearch/transform/metadata_united/default.json

Update current + united metadata transforms to be `settings.unattended: true`.
Related: https://github.com/elastic/security-team/issues/6165
`8.8`

update transforms to be unattended

---

.bumpversion.cfg
package/endpoint/manifest.yml

Update integration category per decision in elastic/ingest-dev#1349.
Related to https://github.com/elastic/integrations/pull/5123.

Update Endpoint package categories

---

.ci/Jenkinsfile

prerelease was only publishing on initial version change since publishing was checking for a version change. this change makes prerelease versions always publish.

always publish prerelease

---

.ci/Jenkinsfile
package/endpoint/manifest.yml

- bump version
- revert jenkins prerelease force publish
bumping prerelease version so we can test `unattended` changes in prerelease. version format changed to `x.x.x-preview-x` as that's how apm is doing it and what we've been referred to as an example. technically apm uses a timestamp at the end but that will require more work.
also reverting jenkins prerelease force publish logic since EPR won't overwrite existing version regardless.

bump prerelease version

---

custom_schemas/custom_base.yml
custom_schemas/custom_endpoint_actions.yml
custom_subsets/elastic_endpoint/actions/actions.yaml
package/endpoint/data_stream/action_responses/fields/fields.yml
package/endpoint/data_stream/actions/fields/fields.yml
schemas/v1/action_responses/action_responses.yaml
schemas/v1/actions/actions.yaml

Closes: https://github.com/elastic/security-team/issues/5929
Not sure if we need rule_name, but from what I remember, it was agreed that we wanted it.

Add fields connected to rules and alerts

---

custom_schemas/custom_responses.yml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/rule_detection_event.yaml

Added fields for Registry Rollback
```json
"@timestamp": "2023-03-24T09:17:08.0Z",
"action": {
"action": "registry_rollback",
"key": {
"actions": [
"Deleted"
],
"path": "\\REGISTRY\\MACHINE\\SOFTWARE\\WOW6432Node\\TestRollback\\2"
}
},
"message": "Successful production registry rollback",
"result": 0
```

Added Registry Rollback Fields to Package

---

package/endpoint/elasticsearch/transform/metadata_current/default.json
package/endpoint/elasticsearch/transform/metadata_united/default.json
package/endpoint/manifest.yml

Revert `unattended` transform option. This change is causing package install to occasionally fail. Since `unattended` means the transform will never throw, fleet doesn't reattempt to reinstall the transform destination indices during transient package install failures leaving the destination indices uncreated.

Revert "update transforms to be unattended (#353)"

---

custom_schemas/custom_dll.yml
custom_schemas/custom_file.yml
custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/alerts/malware_event.yaml
custom_subsets/elastic_endpoint/file/file.yaml
custom_subsets/elastic_endpoint/library/library.yaml
custom_subsets/elastic_endpoint/process/process.yaml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/file/fields/fields.yml
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/malware_event.yaml
schemas/v1/file/file.yaml
schemas/v1/library/library.yaml
schemas/v1/process/process.yaml

This adds `device.file_system_type` field to file/dll/process events and malware alerts. A process event example is [here](https://gist.github.com/Trinity2019/ce9e34e69a9a106694fc0fefa8931261#file-process_event_from_eaf_test_iso_process_strings64-exe_has_device_info-txt-L85-L92). also adding `device.volume_device_type` to malware alerts as it shows up in malware alert, example is [here](https://gist.github.com/Trinity2019/f3b36fabbd38419d63f4231f3e3d1da6#file-malware_alert_process_from_mounted_iso_eaf_test-txt-L169-L176).
Sample document shown in above links.
8.8.0

File system type

---

custom_schemas/custom_responses.yml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/alerts/sample_event.json
package/endpoint/docs/README.md
schemas/v1/alerts/rule_detection_event.yaml

```json
{
"@timestamp": "2023-04-13T16:15:16.0Z",
"action": {
"action": "registry_rollback",
"key": {
"actions": [
"Modified"
],
"path": "\\REGISTRY\\MACHINE\\SOFTWARE\\WOW6432Node\\TestRollback.valuetest",
"values": [
{
"actions": [
"Deleted"
],
"name": "SomeValue"
}
]
}
},
"message": "Successful production registry rollback",
"result": 0
}
```

Added registry rollback fields associated with recovered values

---

custom_schemas/custom_responses.yml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/rule_detection_event.yaml

change `action.key.values` (added in #362) from nested type to object in the alerts index.
alerts index reached maximum (50) nested fields

change action.key.values to object in alerts

---

README.md

Update release instructions in the readme for the new (old) versioning strategy.
Rationale found in #367

change release instructions to use -dev

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

Setup the 8.9 development cycle
`-next` convention is now reserved for use in the `changelog` file, as its intention is to relax the linter:
to allow the top-line `changelog` version to differ from the `manifest` version during development, where the `manifest` file version will likely change with each prerelease. Now the changelog version does not have to constantly change to match.
However, the manifest version _does_ need to continually change to actually perform releases. We cannot overwrite a previous release (even prerelease) with the same version name. So we are going back to the `-dev.N` convention for now, incrementing periodically. This will likely be automated in the future

set up 8.9 dev cycle

---

package/endpoint/manifest.yml

Setup the 8.8 tracking branch for the development cycle
`-next` convention is now reserved for use in the `changelog` file, as its intention is to relax the linter:
to allow the top-line `changelog` version to differ from the `manifest` version during development, where the `manifest` file version will likely change with each prerelease. Now the changelog version does not have to constantly change to match.
However, the manifest version _does_ need to continually change to actually perform releases. We cannot overwrite a previous release (even prerelease) with the same version name. So we are going back to the `-dev.N` convention for now, incrementing periodically. This will likely be automated in the future

setup 8.8.1 dev cycle

---

custom_schemas/custom_endpoint.yml
package/endpoint/data_stream/metrics/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/metrics/metrics.yaml

Adds new metrics fields for the API Event type and the ETW Threat-Intelligence API Event provider.
```
Endpoint.metrics.documents_volume.api_events.sent_bytes
Endpoint.metrics.documents_volume.api_events.sent_count
Endpoint.metrics.documents_volume.api_events.suppressed_bytes
Endpoint.metrics.documents_volume.api_events.suppressed_count
Endpoint.metrics.documents_volume.api_events.sources[].source
Endpoint.metrics.documents_volume.api_events.sources[].sent_bytes
Endpoint.metrics.documents_volume.api_events.sources[].sent_count
Endpoint.metrics.documents_volume.api_events.sources[].suppressed_bytes
Endpoint.metrics.documents_volume.api_events.sources[].suppressed_count
Endpoint.metrics.system_impact.threat_intelligence_events.week_idle_ms …
```

ETW Threat-Intelligence API Event metrics

---

custom_schemas/custom_endpoint.yml
custom_subsets/elastic_endpoint/heartbeat/heartbeat.yaml
package/endpoint/data_stream/heartbeat/fields/fields.yml
package/endpoint/data_stream/heartbeat/sample_event.json
schemas/v1/heartbeat/heartbeat.yaml

This reverts most of https://github.com/elastic/endpoint-package/pull/399
* `Endpoint.state.enabled_features` is removed
* The `custom_documentation/` removal in the original PR is left removed since the data is still now going to a `.logs` index.
See PR
8.10

revert adding Endpoint.state.enabled_features

---

custom_schemas/custom_responses.yml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/alerts/sample_event.json
package/endpoint/docs/README.md
schemas/v1/alerts/rule_detection_event.yaml

Added response fields related to Process Rollback
```json
"Responses": [
{
"@timestamp": "2023-07-19T14:21:05.0Z",
"action": {
"action": "process_rollback",
"process": {
"path": "C:\\Users\\Pawel Mirski\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe"
}
},
"message": "Successful production process rollback",
"result": 0
}
]
```

Added Process Rollback fields

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

- updates min. kibana to `^8.11` (this will cause CI to fail as 8.11 docker images don't exist, which is OK)
- updates package to `8.11.0-preview`. The package linter doesn't accept `-dev` as a valid suffix
- adds matching TBD changelog line, which also quiets the linter

set up 8.11 release cycle

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

Set up the 8.10.x branch for any dev work on patch releases
`-preview` was used as the manifest version instead of `-dev` because of this lint error:
```
6. prerelease tag (dev) should be one of [next, SNAPSHOT], or one of [beta, rc, preview] followed by numbers
```
we used `-next` in the past, but then special handling was added for that one specifically. 
The same postfix was added to the changelog because of this ensuing lint message:
```
4. current manifest version doesn't have changelog entry
```
Both messages went away with this changeset
none

setup 8.10.1 dev cycle

---

catalog-info.yaml

A presence of single whitespace in the owner makes the value a dictionary instead of a string.
This PR fixes it by removing the whitespace.
```json
```

fix buildkite catalog owner

---

custom_documentation/doc/endpoint/file/windows/windows_file_rename.md
custom_documentation/doc/endpoint/metrics/metrics.md
custom_documentation/src/endpoint/data_stream/file/windows/windows_file_rename.yaml
custom_documentation/src/endpoint/data_stream/metrics/metrics.yaml

This adds a few more custom documentation fields for Windows.

add more custom documentation fields on windows

---

package/endpoint/manifest.yml

Update package to specification 3.0.0, and tag capability to security, in order to be installable in a serverless environment

Update package spec and capabilities for serverless filtering

---

custom_documentation/doc/endpoint/process/windows/windows_process_create.md
custom_documentation/src/endpoint/data_stream/process/windows/windows_process_create.yaml

Add missing `process.parent.thread.Ext.call_stack` fields to custom_documentation.
These optional fields have existed since 8.8.0

additional process callstack custom_documentation fields

---

custom_documentation/endpoint/data_stream/process/windows/windows_process_create.yaml
package/endpoint/docs/custom_documentation/process/windows/windows_process_create.md
package/endpoint/manifest.yml

Backport https://github.com/elastic/endpoint-package/pull/435 to 8.10.3.

Backport `custom_documentation` #435 to 8.10.3 

---

custom_documentation/endpoint/data_stream/alerts/macos/macos_malicious_behavior_alert.yaml
custom_documentation/endpoint/data_stream/file/macos/macos_file_delete.yaml
custom_documentation/endpoint/data_stream/file/macos/macos_file_extended_attributes_delete.yaml
custom_documentation/endpoint/data_stream/file/macos/macos_file_launch_daemon.yaml
custom_documentation/endpoint/data_stream/file/macos/macos_file_modification.yaml
custom_documentation/endpoint/data_stream/file/macos/macos_file_mount.yaml
custom_documentation/endpoint/data_stream/file/macos/macos_file_rename.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_fork.yaml
package/endpoint/docs/custom_documentation/alerts/macos/macos_malicious_behavior_alert.md
package/endpoint/docs/custom_documentation/file/macos/macos_file_delete.md
package/endpoint/docs/custom_documentation/file/macos/macos_file_extended_attributes_delete.md
package/endpoint/docs/custom_documentation/file/macos/macos_file_launch_daemon.md
package/endpoint/docs/custom_documentation/file/macos/macos_file_modification.md
package/endpoint/docs/custom_documentation/file/macos/macos_file_mount.md
package/endpoint/docs/custom_documentation/file/macos/macos_file_rename.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_fork.md

```
git cherry-pick 8c8621b
```
Backport https://github.com/elastic/endpoint-package/pull/430 to 8.10.

[8.10 BACKPORT] add more missing custom_documentation fields (#430)

---

custom_documentation/endpoint/data_stream/alerts/windows/windows_malware_alert.yaml
custom_documentation/endpoint/data_stream/file/windows/windows_file_rename.yaml
custom_documentation/endpoint/data_stream/metadata/metadata.yaml
custom_documentation/endpoint/data_stream/metrics/metrics.yaml
custom_documentation/endpoint/data_stream/policy/policy_response.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_already_running.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_exec.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_exit.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_fork.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_gid_change.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_session_id_change.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_text_output.yaml
custom_documentation/endpoint/data_stream/process/linux/linux_process_uid_change.yaml
package/endpoint/docs/custom_documentation/alerts/windows/windows_malware_alert.md
package/endpoint/docs/custom_documentation/file/windows/windows_file_rename.md
package/endpoint/docs/custom_documentation/metadata/metadata.md
package/endpoint/docs/custom_documentation/metrics/metrics.md
package/endpoint/docs/custom_documentation/policy/policy_response.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_already_running.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_exec.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_exit.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_fork.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_gid_change.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_session_id_change.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_text_output.md
package/endpoint/docs/custom_documentation/process/linux/linux_process_uid_change.md

This pulls all `custom_documentation/` from `main` into `8.10`. I did the below steps
```
git checkout main
cp -r custom_documentation/src /tmp/backup
git checkout 8.10
git checkout -b add-all-custom-doc-from-main-to-8.10
rm -rf custom_documentation/endpoint
cp -r /tmp/backup/endpoint custom_documentation/endpoint
make clean all
git add custom_documentation package
git commit
```

add all custom_documentation from main into 8.10

---

package/endpoint/data_stream/metadata/manifest.yml

A change in yaml formatting, removing `key1.key2` dotted-key style, and changing to the verbose version
this is a required formatting enforced by package-spec 3.0
8.12

Reformat metadata yaml, removed dotted-keys

---

custom_schemas/custom_endpoint.yml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/alerts/sample_event.json
package/endpoint/data_stream/policy/fields/fields.yml
package/endpoint/data_stream/policy/sample_event.json
schemas/v1/alerts/malware_event.yaml
schemas/v1/alerts/memory_protection_event.yaml
schemas/v1/alerts/ransomware_event.yaml
schemas/v1/policy/policy.yaml

Add artifact snapshot date indicator. When artifacts are not pinned to any specific snapshot date the keyword 'latest' is used.
Add artifact up-to-date age indicator. It's equal to number of days since the local artifacts copy at Endpoint side was last time deemed up-to-date (the date when either Endpoint updated the artifacts or verified that it's artifacts are up-to-date with Elastic CDN).
Note, when artifacts are pinned to a specific snapshot date, the age always equal to the numbers of days since that date. In addition the initial artifacts shipped with the installation package age is equal to the number of days since the package creation date (endpoint build date).
Artifacts made or verified to be up-to-date today:
`"Endpoint.policy.applied.artifacts.global.update_age": 0`
Artifacts …

artifacts manifest update age, snapshot date

---

package/endpoint/data_stream/action_responses/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/actions/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/alerts/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/api/_dev/test-common-config.yml
package/endpoint/data_stream/collection/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/file/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/heartbeat/manifest.yml
package/endpoint/data_stream/library/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/metadata/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/metrics/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/network/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/policy/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/process/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/registry/_dev/test/pipeline/test-common-config.yml
package/endpoint/data_stream/security/_dev/test/pipeline/test-common-config.yml

replace more instances of yaml dotted-key format to multiline format (for package-spec 3.0)
the semantics of this PR are intended to be identical, only formatting changes

Replace more dotted keys

---

package/endpoint/elasticsearch/transform/metadata_current/transform.yml
package/endpoint/elasticsearch/transform/metadata_united/transform.yml

the `unattended` setting was developed for these transforms as the ideal use-case. There were previous transient install issues with using in the past, that may have been resolved with https://github.com/elastic/elasticsearch/pull/101627
Local testing has so far resulted in consistent destination index being created, and working transforms:
8.12

Enable Unattended Transforms

---

custom_subsets/elastic_endpoint/api/api.yaml
package/endpoint/data_stream/api/fields/fields.yml
package/endpoint/data_stream/api/sample_event.json
schemas/v1/api/api.yaml

Add missing `[Target.]process.Ext.memory_region` fields to api events.
These optional fields were introduced in 8.11.0

Add memory_region to api events

---

.github/CODEOWNERS

Change owner of the `custom_documentation` folder (and all contents) to the endpoint team.
This folder and its contents are _not_ shipped into EPR, are _not_ linted by `elastic-package` and are _not_ regulated or restricted by `package-spec`. Its influence is entirely external.  Defend workflows team has no need to have oversight over the custom docs

make endpoint team sole owners of custom docs

---

.ci/Jenkinsfile
package/endpoint/manifest.yml

`8.12.0-preview.1` was pushed from `main`,  breaking a lot of tests, as serverless was still installing prerelease versions in (at least) tests.
Rolling back all changes to `main` since 8.11 branch was cut was a messier process than releasing an `8.12.0-preview.2` from here.
So this PR will create an 8.12 prerelease, with "known good" contents, which should be released on merge

Push an 8.12 preview from 8.11 changeset

---

package/endpoint/manifest.yml

- [Integrations that run as root should mark themselves so](https://github.com/elastic/integrations/issues/8642)
- [Kibana will display root requirements](https://github.com/elastic/kibana/pull/170478)
- The field is [supported by package-spec](https://github.com/elastic/package-spec/pull/605)
8.12

mark integration as requiring root-level agent

---

.buildkite/scripts/find_oldest_supported_version.py
custom_schemas/custom_file.yml
custom_subsets/elastic_endpoint/file/file.yaml
package/endpoint/data_stream/file/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/file/file.yaml

Add Original Extension field for file rename events
```json
```

Original Extension field for file rename events

---

package/endpoint/data_stream/api/fields/fields.yml
schemas/v1/api/api.yaml

8.12 branch failing from diffs on these files. Looking to reconcile
```
21:29:07  :100644 100644 a5e712032f1cac5b9d7e03da8c02f0abc6584c02 0000000000000000000000000000000000000000 M	package/endpoint/data_stream/api/fields/fields.yml
21:29:07  :100644 100644 407721a6722d79f1581e911b9bfd7086f3ea6d8d 0000000000000000000000000000000000000000 M	schemas/v1/api/api.yaml
```
8.12

remove obj type for api generated files

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

setup kibana min version, package version, and changelog for next dev series

Setup 8.13 cycle

---

catalog-info.yaml

This PR fixes Buildkite trigger based on branch change. It must be a explicit list of branch separated by space.

fix branch_configuration

---

.ci/jobs/endpoint-package-mbp.yml

https://github.com/elastic/security-team/issues/6786
We confirmed that we are able to publish artifact using Buildkite pipeline https://buildkite.com/elastic/endpoint-package/builds/232, so this is a follow up PR that disables Jenkins pipeline.
Prior to merging this, someone with admin access to the repository must switch PR branch restriction to new Buildkite pipeline so that a PR is no longer blocked on Jenkins, but Buildkite CI.

disable jenkins

---

.buildkite/scripts/find_oldest_supported_version.py
catalog-info.yaml

Integration team used the same file .buildkite/scripts/find_oldest_supported_version.py, and made update to it. https://github.com/elastic/integrations/blob/main/.buildkite/scripts/find_oldest_supported_version.py
This file picks up some of the changes they introduced.
Also adding some condition logic to prevent accidental cancelation of main and 8.12 branch CI job.
Buildkite only changes

Fix kibana version condition and additional buildkite settings

---

catalog-info.yaml

8.13 release happened, but new buildkite configs were not updated to treat the `8.13` release branch.. as a release branch.
This PR will be backported to that branch as well

Add missing branch defs

---

catalog-info.yaml
custom_documentation/doc/endpoint/security/windows/windows_security_log_off.md
custom_documentation/doc/endpoint/security/windows/windows_security_log_on.md
custom_documentation/src/endpoint/data_stream/security/windows/windows_security_log_off.yaml
custom_documentation/src/endpoint/data_stream/security/windows/windows_security_log_on.yaml
custom_subsets/elastic_endpoint/security/security.yaml
package/endpoint/data_stream/security/fields/fields.yml
package/endpoint/data_stream/security/sample_event.json
package/endpoint/docs/README.md
schemas/v1/security/security.yaml

This adds the "effective" field to the user field of security events. 
```
{
"@timestamp": "2024-03-28T13:57:06.9120679Z",
"agent": {
"id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
"type": "endpoint",
"version": "8.14.0-SNAPSHOT"
},
"data_stream": {
"dataset": "endpoint.events.security",
"namespace": "default",
"type": "logs"
},
"ecs": {
"version": "8.10.0"
},
"elastic": {
"agent": {
"id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
}
},
"event": {
"action": "log_on",
"category": [
"authentication",
"session"
],
"created": "2024-03-28T13:57:06.9120679Z",
"dataset": "endpoint.events.security",
"id": "NUJr8jg5OdZe9mSa++++++EF",
"kind": "event",
"module": "endpoint",
"outcome": "success",
"sequence": 1234,
"type": [
"start"
]
},
"host": {
"architecture": "x86_64",
"hostname": …
```

Added 'effective' user field.

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

`8.14.0` has been released. An `8.14` branch has been created for any further releases on that line. This converts the `main` branch to the 8.15 cycle now

Prepare main branch for next release cycle

---

custom_subsets/elastic_endpoint/api/api.yaml
package/endpoint/data_stream/api/fields/fields.yml
schemas/v1/api/api.yaml

Adds `event.dataset` to `api` datastream. Exists in most others
Fixes #492
8.15
- ~~[ ] If these field(s) are "exception"-able, I made a companion PR to Kibana adding it (see [Readme](https://github.com/elastic/endpoint-package#exceptionable))~~
- ~~[ ] If this is a `metadata` change, I also updated both transform destination schemas to match~~

Add event.dataset to api datastream

---

custom_schemas/custom_base.yml
custom_subsets/elastic_endpoint/heartbeat/heartbeat.yaml
package/endpoint/data_stream/heartbeat/fields/fields.yml
package/endpoint/data_stream/heartbeat/sample_event.json
schemas/v1/heartbeat/heartbeat.yaml

Adds a new boolean field `billable` to the heartbeat mapping. This field is used to determine whether a particular heartbeat document should be included in billing calculations.
```json
{
"@timestamp": "2023-07-18T20:40:09.279939Z",
"agent": {
"id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
},
"data_stream": {
"dataset": "endpoint.heartbeat",
"namespace": "default",
"type": ".logs"
},
"message": "Endpoint heartbeat",
"event": {
"ingested": "2023-07-18T20:40:09.279939Z"
},
"billable": true
}
```
`8.15`

add heartbeat `billable` field

---

custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/api/api.yaml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/api/fields/fields.yml
package/endpoint/data_stream/api/sample_event.json
package/endpoint/data_stream/file/fields/fields.yml
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/registry/fields/fields.yml
schemas/v1/alerts/memory_protection_event.yaml
schemas/v1/api/api.yaml
schemas/v1/file/file.yaml
schemas/v1/library/library.yaml
schemas/v1/process/process.yaml
schemas/v1/registry/registry.yaml

Add call_stack_summary to API events. This field is indexed for other event types.

index call_stack_summary in API events

---

custom_documentation/doc/endpoint/library/windows/windows_library_load.md
custom_documentation/src/endpoint/data_stream/library/windows/windows_library_load.yaml
custom_subsets/elastic_endpoint/library/library.yaml
package/endpoint/data_stream/library/fields/fields.yml
package/endpoint/data_stream/library/sample_event.json
package/endpoint/data_stream/process/sample_event.json
package/endpoint/docs/README.md
schemas/v1/library/library.yaml

Add `process.Ext.protection` to Windows library events - added in 8.15.1.

Add process.Ext.protection to Windows library events

---

.buildkite/sign_and_publish.yml.py

Turns out there is another branch name check, that sets `DRY_RUN=true` if not "main". So `8.15.1` did not get pushed after merging #530 
Manually updating this on `8.15` branch for now, but will be included in the future release branch PRs to do this automatically

correct branch in publishing pipeline

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

sets up dev cycle for any changes after `8.15.1` release
do not merge until `8.15.1` release is complete

setup next dev version

---

package/endpoint/changelog.yml

What's the opposite of a backport? forward-port?
This pulls forward the changelog entry from the `8.15.1` release to the `main` branch, so changelog history is preserved

pull-forward 8.15.1 changelog

---

custom_documentation/doc/endpoint/alerts/windows/windows_malware_alert.md
custom_documentation/doc/endpoint/security/windows/windows_security_log_off.md
custom_documentation/doc/endpoint/security/windows/windows_security_log_on.md

Update custom documentation. There was discrepancy between `custom_docucmentation/src/` and `custom_documentation/doc`. The latter didn't include latest updates.
It turns out that it was caused by running `make` instead of `make clean all`

custom documentation wasn't properly rendered

---

custom_documentation/doc/endpoint/file/linux/linux_file_create.md
custom_documentation/doc/endpoint/file/linux/linux_file_rename.md
custom_documentation/doc/endpoint/file/macos/macos_file_access.md
custom_documentation/doc/endpoint/file/macos/macos_file_extended_attributes_delete.md
custom_documentation/doc/endpoint/file/macos/macos_file_modification.md
custom_documentation/doc/endpoint/file/macos/macos_file_rename.md
custom_documentation/doc/endpoint/file/windows/windows_file_create.md
custom_documentation/doc/endpoint/file/windows/windows_file_modification.md
custom_documentation/doc/endpoint/file/windows/windows_file_open.md
custom_documentation/doc/endpoint/file/windows/windows_file_overwrite.md
custom_documentation/doc/endpoint/file/windows/windows_file_rename.md
custom_documentation/src/endpoint/data_stream/file/linux/linux_file_create.yaml
custom_documentation/src/endpoint/data_stream/file/linux/linux_file_rename.yaml
custom_documentation/src/endpoint/data_stream/file/macos/macos_file_access.yaml
custom_documentation/src/endpoint/data_stream/file/macos/macos_file_delete.yaml
custom_documentation/src/endpoint/data_stream/file/macos/macos_file_extended_attributes_delete.yaml
custom_documentation/src/endpoint/data_stream/file/macos/macos_file_modification.yaml
custom_documentation/src/endpoint/data_stream/file/macos/macos_file_rename.yaml
custom_documentation/src/endpoint/data_stream/file/windows/windows_file_create.yaml
custom_documentation/src/endpoint/data_stream/file/windows/windows_file_modification.yaml
custom_documentation/src/endpoint/data_stream/file/windows/windows_file_open.yaml
custom_documentation/src/endpoint/data_stream/file/windows/windows_file_overwrite.yaml
custom_documentation/src/endpoint/data_stream/file/windows/windows_file_rename.yaml

- https://github.com/elastic/endpoint/issues/78
This is not a schema change.
Users will be able to opt into `file.hash.sha256` in additional types of file events.  It's already in our schema.  This PR adds it to `custom_documentation`.

Optional File Event Hashes

---

custom_documentation/doc/endpoint/alerts/linux/linux_malware_alert.md
custom_documentation/doc/endpoint/alerts/macos/macos_malware_alert.md
custom_documentation/src/endpoint/data_stream/alerts/linux/linux_malware_alert.yaml
custom_documentation/src/endpoint/data_stream/alerts/macos/macos_malware_alert.yaml
custom_schemas/custom_malware_signature.yml
package/endpoint/data_stream/api/fields/fields.yml
schemas/v1/api/api.yaml

We're getting some EAF errors in `8.15` due to missing schema and custom docs for `file.Ext.malware_signature.secondary`:
> E       AssertionError: Found documents not complying with ECS, count: 1, schema violation keys: {'file.Ext.malware_signature.secondary'}, check log for details. Documents written to ecs_schema_violations.ndjson
>
> E       Found documents with fields missing custom documentation, count: 1, undocumented keys: {'file.Ext.malware_signature.secondary.signature.id', 'file.Ext.malware_signature.secondary.matches', 'file.Ext.malware_signature.secondary.signature.hash.sha256', 'file.Ext.malware_signature.secondary.signature.name'}. Documents written to custom_documentation_violations.ndjson
The tests are failing in `8.15` too, so we should backport these changes.  We still …

Secondary Malware Signature Fields

---

custom_documentation/doc/endpoint/network/windows/windows_network_dns_lookup_result.md
custom_documentation/src/endpoint/data_stream/network/windows/windows_network_dns_lookup_result.yaml
package/endpoint/data_stream/network/sample_event.json

Add `dns.resolved_ip` to Windows custom docs to address recent regression.  Also, we didn't have any DNS fields in the sample network event.

Add dns.resolved_ip to Windows custom docs to address recent regression.

---

custom_schemas/custom_api.yml
custom_schemas/custom_call_stack.yml
custom_schemas/custom_endpoint.yml
custom_schemas/custom_memory_protection.yml
custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/api/api.yaml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/api/fields/fields.yml
package/endpoint/data_stream/api/sample_event.json
package/endpoint/docs/README.md
schemas/v1/alerts/memory_protection_event.yaml
schemas/v1/api/api.yaml
schemas/v1/file/file.yaml
schemas/v1/library/library.yaml
schemas/v1/metadata/metadata.yaml
schemas/v1/metrics/metrics.yaml
schemas/v1/policy/policy.yaml
schemas/v1/process/process.yaml
schemas/v1/registry/registry.yaml

* Add new DeviceIoControl event fields
* Add new final_user_module fields
* Add short descriptions for all fields. 
Note - custom documentation has not yet been updated.
```json
{
"dll": {
"Ext": {
"code_signature": [
{
"exists": true,
"status": "trusted",
"subject_name": "Microsoft Windows",
"trusted": true
}
]
},
"hash": {
"sha256": "8b9731a4b83e801cda7b918f8194608e91f86b3a86ffb6bb24230b1cc28e1a54"
},
"path": "c:\\windows\\system32\\drivers\\pktmon.sys"
},
"message": "Endpoint API event - DeviceIoControl",
"process": {
"Ext": {
"api": {
"metadata": {
"security_descriptor": "O:BAG:SYD:P(A;;FA;;;SY)(A;;FA;;;BA)S:AI(ML;;NW;;;LW)"
},
"name": "DeviceIoControl",
"parameters": {
"device": "\\Device\\PktMonDev",
"io_control_code": 27365
},
"summary": "DeviceIoControl( \\Device\\PktMonDev, …
```

[8.16] API - DeviceIoControl events and new final_user_module fields

---

custom_schemas/custom_winlog.yml
custom_subsets/elastic_endpoint/security/security.yaml
package/endpoint/data_stream/security/fields/fields.yml
package/endpoint/data_stream/security/sample_event.json
package/endpoint/docs/README.md
schemas/v1/security/security.yaml

This PR adds a custom schema for `winlog` that the security auditing provider produces.
The reason for the uncommon casing is that we're trying to match the field that are defined in `winlogbeat`: https://www.elastic.co/guide/en/beats/winlogbeat/current/exported-fields-winlog.html
Here is an example of the  (`winlog.event_data.PrivilegeList`) that will be added by this PR. 
```json
"winlog": {
"event_data": {
"PrivilegeList": [
"SeSecurityPrivilege",
"SeTakeOwnershipPrivilege",
"SeLoadDriverPrivilege",
"SeBackupPrivilege",
"SeRestorePrivilege",
"SeDebugPrivilege",
"SeSystemEnvironmentPrivilege",
"SeImpersonatePrivilege",
"SeDelegateSessionUserImpersonatePrivilege"
]
}
}
```
8.16

Add winlog.event_data.PrivilegeList to security events

---

custom_documentation/doc/endpoint/alerts/linux/linux_malware_alert.md
custom_documentation/src/endpoint/data_stream/alerts/linux/linux_malware_alert.yaml

Include policy `name` and policy `id` in alerts. 
Those fields are already mapped but were never sent, so we only need to update custom documentation now.

Include policy name in alerts

---

custom_documentation/doc/endpoint/api/windows/windows_api_credential_access.md
custom_documentation/doc/endpoint/api/windows/windows_api_threat_intelligence.md
custom_documentation/doc/endpoint/api/windows/windows_api_win32k.md
custom_documentation/doc/endpoint/api/windows/windows_api_wmi.md
custom_documentation/src/endpoint/data_stream/api/windows/windows_api_credential_access.yaml
custom_documentation/src/endpoint/data_stream/api/windows/windows_api_threat_intelligence.yaml
custom_documentation/src/endpoint/data_stream/api/windows/windows_api_win32k.yaml
custom_documentation/src/endpoint/data_stream/api/windows/windows_api_wmi.yaml

Add `Target.process.Ext.protection` to custom docs to fix EAF failure:
```
AssertionError: Found documents with fields missing custom documentation, count: 1, undocumented keys: {'Target.process.Ext.protection'}. Documents written to custom_documentation_violations.ndjson
```
8.18.  This PR is a candidate for 7.17 backports.

[8.18] Add `Target.process.Ext.protection` to API event custom docs

---

.buildkite/scripts/find_oldest_supported_version.py
package/endpoint/manifest.yml

Update Kibana version constraint to include `9.0`. This will allow this version of the package (8.18.0) to function in the 9.x stack, prior to upgrade.
The constraint `^9.0.0` applies to _every_ version under the major number `9`, so this package will work for jumping to `9.1`, `9.2`, ... etc. We will not need to bump the "9" portion of this constraint for `8.19` package.
8.18.0

update version constraint to be upgradable to 9.0, bump pre

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

Updates `main` to now target stack 9
`8.x` has been branched, to handle `8.18` and `8.19` releases, backports will go to `8.x`.
9.0

Update branch target for major v9

---

.buildkite/pipeline.yml.py

Release pipeline was not included for new `8.x` branch

Add 8.x release pipeline

---

.buildkite/pipeline.yml.py
catalog-info.yaml
package/endpoint/changelog.yml

This is a back- (forward?) port of changes from `8.x` and `8.18` release, into main
- Changelog release notes from 8.18.0 release
- #586 fix to release pipeline
- adding release branches to catalog-info

Catch up from 8.18

---

.buildkite/sign_and_publish.yml.py

on branches like `8.x`, package release would happen in a dry run mode
So the on-merge step on the `8.x` branch right now did not publish the `8.18.0` package, epr still reflects `8.17.0` as current.
Making sure these specific branches allow live deployments may fix. This change will be backported to `8.x` branch

disable DRY_RUN on releasable branches

---

.buildkite/sign_and_publish.yml.py

This is a backport of #589 to the `8.x` branch

[8.x][backport] disable DRY_RUN on releasable branches (#589)

---

.buildkite/pipeline.yml.py
.buildkite/sign_and_publish.yml.py
catalog-info.yaml
package/endpoint/changelog.yml
package/endpoint/manifest.yml

Backports current state of `8.x`, which is release point for 8.18.0, to the branch `8.18`
CI release and publish step from this point in `8.x` ran, and should have published `8.18.0` package, but epr is not reflecting that. backporting may trigger another release

[backport] 8.18 release

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

Package `v9.0.0` release is out. The `9.0` _branch_ is now used as the target for any additions or backports that need to go out to the `9.0`-series stack.
This change sets up the `9.0` branch to be in the dev/prep cycle to include any new changes as the next patch release (`9.0.1`)

prepare 9.0 branch for patch release dev work cycle

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

Now that `v9.0.0` (package) has been released, the `9.0` _branch_ has been cut to issue any followup releases to the `9.0` stack. Main branch now targets the next stack release, `9.1`.

update main branch target for 9.1 stack cycle

---

custom_schemas/custom_memory_region.yml
custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/alerts/sample_event.json
package/endpoint/data_stream/api/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/alerts/memory_protection_event.yaml
schemas/v1/api/api.yaml

Add missing backport to 9.0 (backported to 8.18, 8.x already)

[backport][9.0] Change the size of region_start_bytes + add the field to the alert data stream (#591)

---

custom_documentation/doc/endpoint/metrics/metrics.md

For whatever reason, `make` is generating this field ordering change. This PR is just committing `make` on the `9.0` branch to clear up CI

[9.0] Cleanup format

---

doc_templates/endpoint/docs/README.md
package/endpoint/docs/README.md

Adds a notice to the readme, about the bug effects from https://github.com/elastic/kibana/pull/217959
9.0, 8.18, 8.17, 8.16 (note: _not_ 9.1)
The merge target to start is therefore `9.0`, not `main`, and then we will cherry-pick backport to the previous release branches

add prebuilt rules bug banner

---

custom_documentation/doc/endpoint/metrics/metrics.md
custom_documentation/src/endpoint/data_stream/metrics/metrics.yaml

Add Endpoint.metrics.queue_metric.* to custom docs to fix EAF failures:
```
AssertionError: Found documents with fields missing custom documentation, count: 2, undocumented keys: {'Endpoint.metrics.queue_metrics.user.async_kernel_event_queue.drops', 'Endpoint.metrics.queue_metrics.user.async_kernel_event_queue.size', 'Endpoint.metrics.queue_metrics.kernel.send_to_user_queue.drops', 'Endpoint.metrics.queue_metrics.kernel.send_to_user_queue.size'}. Documents written to custom_documentation_violations.ndjson
```
8.17.6.

Add metrics queues custom docs

---

custom_documentation/doc/endpoint/alerts/windows/windows_malicious_behavior_alert.md
custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malicious_behavior_alert.yaml

Some rules have `threat.technique.subtechnique: null`.  When Endpoint passes that through to Kibana, it results in a custom doc failure.

Fix Windows behavior alert custom doc

---

custom_documentation/doc/endpoint/file/windows/windows_file_modification.md
custom_documentation/doc/endpoint/file/windows/windows_file_overwrite.md
custom_documentation/src/endpoint/data_stream/file/windows/windows_file_modification.yaml
custom_documentation/src/endpoint/data_stream/file/windows/windows_file_overwrite.yaml

`process.command_line` was missing from custom docs for two types of file events.

Add process.command_line to some windows file events

---

custom_schemas/custom_action_policy.yml
custom_schemas/custom_action_space.yml
custom_subsets/elastic_endpoint/actions/actions.yaml
package/endpoint/data_stream/actions/fields/fields.yml
package/endpoint/data_stream/actions/sample_event.json
schemas/v1/actions/actions.yaml

Adds a space-awareness field (`originSpaceId`) as well as some policy-related IDs to action request documents
included in [`package/endpoint/data_stream/actions/sample_event.json`](https://github.com/elastic/endpoint-package/compare/actions-log-spaces?expand=1#diff-75c3868aefbfe12fdad1d549144e903bc85355948d8e5c8c30723e0eb029d179)
9.1

Actions log spaces

---

custom_subsets/elastic_endpoint/api/api.yaml
package/endpoint/data_stream/api/fields/fields.yml
schemas/v1/api/api.yaml

- https://github.com/elastic/endpoint-package/issues/630
Add `event.provider` to API events to fix the issue reported in https://github.com/elastic/endpoint-package/issues/630

Add `event.provider` to API events

---

custom_documentation/doc/endpoint/api/windows/windows_api_threat_intelligence.md
custom_documentation/doc/endpoint/api/windows/windows_api_win32k.md
custom_documentation/doc/endpoint/process/windows/windows_process_already_running.md
custom_documentation/doc/endpoint/process/windows/windows_process_create_and_exit.md
custom_documentation/src/endpoint/data_stream/api/windows/windows_api_threat_intelligence.yaml
custom_documentation/src/endpoint/data_stream/api/windows/windows_api_win32k.yaml
custom_documentation/src/endpoint/data_stream/process/windows/windows_process_already_running.yaml
custom_documentation/src/endpoint/data_stream/process/windows/windows_process_create_and_exit.yaml
custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/alerts/rule_detection_event.yaml
custom_subsets/elastic_endpoint/api/api.yaml
custom_subsets/elastic_endpoint/process/process.yaml
package/endpoint/data_stream/alerts/fields/fields.yml
package/endpoint/data_stream/api/fields/fields.yml
package/endpoint/data_stream/api/sample_event.json
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/process/sample_event.json
package/endpoint/docs/README.md
package/endpoint/manifest.yml
schemas/v1/alerts/rule_detection_event.yaml
schemas/v1/api/api.yaml
schemas/v1/process/process.yaml

Add additional `desktop_name` field for process creation event telemetry.

Add fields for additional desktop_name process event field

---

custom_schemas/custom_action_space.yml
custom_subsets/elastic_endpoint/actions/actions.yaml
package/endpoint/data_stream/actions/fields/fields.yml
package/endpoint/data_stream/actions/sample_event.json
schemas/v1/actions/actions.yaml

Adds field `tags` to actions
9.1

Add tags to action request documents

---

package/endpoint/elasticsearch/index_template/metrics-metadata-united.json

adds mapping for `united.agent.namespaces` in united metadata index template.
```json
{
...,
namespaces: ["default", "foo"]
...,
}
```
`9.1`

add mapping for united.agent.namespaces

---

package/endpoint/changelog.yml

adding changelog entries as a separate step for release.  the entire changelog here also applies to the changes from `8.18` -> `8.19`, so this can be backported with the version label changed

Update changelog for 9.1

---

custom_documentation/doc/endpoint/metrics/metrics.md
custom_documentation/src/endpoint/data_stream/metrics/metrics.yaml

This adds `sources` info to process events in the metrics document.
```json
"process_events": {
"sent_bytes": 1478944,
"sent_count": 732,
"sources": [  <--- new for process events
{
"sent_bytes": 0,
"sent_count": 0,
"source": "shmget",
"suppressed_bytes": 0,
"suppressed_count": 1
}
],
"suppressed_bytes": 0,
"suppressed_count": 7
}
```
This change allows for data based diag->prod decisions for new Linux process events: load_module, ptrace, and shmget
8.19.1, 9.1.1, 9.2.0

Enhance process event metrics

---

package/endpoint/changelog.yml
package/endpoint/manifest.yml

Releases package version `9.1.1` containing #650

Release 9.1.1

---

custom_documentation/doc/endpoint/process/linux/linux_process_ptrace.md
custom_documentation/src/endpoint/data_stream/process/linux/linux_process_ptrace.yaml
custom_schemas/custom_process.yml
custom_subsets/elastic_endpoint/process/process.yaml
package/endpoint/data_stream/process/fields/fields.yml
package/endpoint/data_stream/process/sample_event.json
package/endpoint/docs/README.md
schemas/v1/process/process.yaml

Add more fields for [ptrace](https://man7.org/linux/man-pages/man2/ptrace.2.html) events. For example, when the request is `PTRACE_POKETEXT`, we can know the address and the value being changed in the traced process.
```json
{
"@timestamp":"2025-09-03T18:13:08.8118015Z",
"agent":{
"id":"",
"type":"endpoint",
"version":"9.2.0-SNAPSHOT"
},
"data_stream":{
"dataset":"",
"namespace":"",
"type":""
},
"ecs":{
"version":"8.10.0"
},
"elastic":{
"agent":{
"id":""
}
},
"event":{
"action":["ptrace"],
"category":["process"],
"dataset":"",
"id":"O9W37uzNQh7M/SpY+++++++8",
"kind":"event",
"module":"endpoint",
"outcome":"unknown",
"sequence":388,
"type":["start"]
},
"host":{
"id":"",
"name":"",
"os":{
"type":"linux"
}
},
"message":"Endpoint process event",
"process":{
"Ext":{
"ptrace":{ …
```

Add process.Ext.ptrace.addr and .data

---

custom_documentation/doc/endpoint/metadata/metadata.md
custom_documentation/doc/endpoint/policy/policy_response.md
custom_documentation/src/endpoint/data_stream/metadata/metadata.yaml
custom_documentation/src/endpoint/data_stream/policy/policy_response.yaml
custom_schemas/custom_endpoint.yml
custom_subsets/elastic_endpoint/metadata/metadata.yaml
custom_subsets/elastic_endpoint/policy/policy.yaml
package/endpoint/data_stream/metadata/fields/fields.yml
package/endpoint/data_stream/policy/fields/fields.yml
package/endpoint/docs/README.md
schemas/v1/metadata/metadata.yaml
schemas/v1/policy/policy.yaml

Add `Orphaned` status indicator to Endpoint policy response
Add tamper protection status indicator to Endpoint policy response
`Endpoint.state.orphaned: true`
`Endpoint.state.tamper_protection: true`
```json
"state": {
"isolation": false,
"orphaned": true,
"tamper_protection": false
},
```

custom_documentation update, policy state orphaned

---

custom_documentation/doc/endpoint/api/windows/windows_api_firewall_anti_tamper.md
custom_documentation/doc/endpoint/policy/policy_response.md
custom_documentation/src/endpoint/data_stream/api/windows/windows_api_firewall_anti_tamper.yaml
custom_documentation/src/endpoint/data_stream/policy/policy_response.yaml
custom_schemas/custom_endpoint.yml
package/endpoint/data_stream/policy/fields/fields.yml
package/endpoint/data_stream/policy/sample_event.json
schemas/v1/policy/policy.yaml

Add `firewall_anti_tamper` fields to production configuration.

Add firewall_anti_tamper fields to production configuration
