elastic/endpoint-package

Makefile, docker-compose.yml
Cleaning up some of the targets and commenting things.
=> Doing some cleanup and commenting

custom_schemas/custom_endpoint.yml, generated/policy/ecs/ecs_flat.yml, generated/policy/ecs/subset/policy/ecs_flat.yml, generated/policy/elasticsearch/7/template.json, package/endpoint/data_stream/policy/fields/fields.yml, schemas/v1/policy/policy.yaml
Adds a new section in the Policy response for the register as AV feature
=> add antivirus registration section in policy response

README.md
Correcting the readme instructions for `staging` -> `snapshot`
=> Updating readme with snapshot instructions

custom_schemas/custom_file.yml, custom_subsets/elastic_endpoint/file/file.yaml, generated/file/ecs/ecs_flat.yml, generated/file/ecs/subset/file/ecs_flat.yml, generated/file/elasticsearch/7/template.json, package/endpoint/data_stream/file/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/file/file.yaml
Adding fields for ransomware file event replay.
=> Ransomware file fields

package/endpoint/elasticsearch/index_template/metrics-metadata-current.json, package/endpoint/elasticsearch/transform/metadata_current/default.json
=> [7.11] expand transform index search to account for namespaces (#122)

custom_subsets/elastic_endpoint/library/library.yaml, generated/library/ecs/ecs_flat.yml, generated/library/ecs/subset/library/ecs_flat.yml, generated/library/elasticsearch/7/template.json, package/endpoint/data_stream/library/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/library/library.yaml
Backports the following commits to 7.11:
- Mapping dll.code_sig (#131)
=> [7.11] Mapping dll.code_sig (#131)

package/endpoint/manifest.yml
Bumping the stack version in preparation for the transform PR: https://github.com/elastic/endpoint-package/pull/124
=> Bumping stack version to prep 7.12 release

.gitattributes
See https://github.com/elastic/endpoint-package/pull/137#discussion_r607067783
=> Show some generated output in diffs

package/endpoint/manifest.yml
=> [7.14] take endpoint security out of beta (#160)

package/endpoint/elasticsearch/transform/metadata_current/default.json
=> [7.14] Set transform pivot to elastic.agent.id (#163)

custom_schemas/custom_endpoint.yml, generated/policy/ecs/ecs_flat.yml, generated/policy/ecs/subset/policy/ecs_flat.yml, generated/policy/elasticsearch/7/template.json, package/endpoint/data_stream/policy/fields/fields.yml, schemas/v1/policy/policy.yaml
This PR updates policy response to include memory_protection plugin
Issue: https://github.com/elastic/endpoint-dev/issues/8761
=> added production memory_protection policy response

custom_schemas/custom_file.yml, custom_subsets/elastic_endpoint/file/file.yaml, generated/file/ecs/ecs_flat.yml, generated/file/ecs/subset/file/ecs_flat.yml, generated/file/elasticsearch/7/template.json, generated/policy/ecs/ecs_flat.yml, generated/policy/ecs/subset/policy/ecs_flat.yml, package/endpoint/data_stream/file/fields/fields.yml, package/endpoint/data_stream/policy/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/file/file.yaml, schemas/v1/policy/policy.yaml
https://github.com/elastic/endpoint-dev/issues/9164
Adds malware_signature fields to endpoint-package
=> ISSUE-9164: malware signature fields

package/endpoint/manifest.yml
package `0.22.x` series will target kibana `7.16`
=> bump kibana to next release

Makefile
some makefile cleanup, but chiefly fixes the problem where bumping to a new ECS version does not make sure other's `out/ecs` git repo has fetched lately to even _have_ the new tag.
It does this by making sure the git ref exists in `.git`. If it's not there, fetch (+tags) to create it.
=> [Maintenance] Pull ECS tags when missing

package/endpoint/elasticsearch/transform/metadata_current/default.json
Noticed this when adding the next transform. The existing transform might need some clarity. Open to other suggestions
=> Better description for the "latest" transform

custom_schemas/custom_malware_signature.yml, generated/alerts/ecs/ecs_flat.yml, generated/alerts/elasticsearch/7/template.json, package/endpoint/data_stream/alerts/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/alerts/memory_protection_event.yaml
=> [7.16] set malware_signature.primary.matches as unindexed keyword (#212)

package/endpoint/changelog.yml
=> [7.16] add 1.2.2 changelog entry (#215)

package/endpoint/manifest.yml
=> now bump to 8.0.0 for 1.4 series

.github/PULL_REQUEST_TEMPLATE, README.md
Improving the documentation on how to make fields fill in the Exceptions menu in Kibana
=> improve documentation for adding fields to exceptions dropdown

.ci/jobs/defaults.yml, .ci/jobs/endpoint-package-mbp.yml
A new project has been added to the CI.
=> [jjbb][beats-ci] endpoint-package

package/endpoint/manifest.yml
=> bump kibana.version > ^8.3

.bumpversion.cfg
fix bump2version config for added cloud category in manifest.
=> update bump2version config for manifest change

package/endpoint/manifest.yml
Update minimum kibana version for upcoming release
8.4
=> kibana compat bump for 8.4 release

package/endpoint/changelog.yml
Update the changelog for 8.4 release
=> Update Changelog for 8.4

.ci/Jenkinsfile
=> [backport][8.4] Add release branches to deploy instructions (#279)

custom_schemas/custom_dll.yml, custom_schemas/custom_file.yml, custom_schemas/custom_process.yml, custom_subsets/elastic_endpoint/file/file.yaml, custom_subsets/elastic_endpoint/library/library.yaml, custom_subsets/elastic_endpoint/process/process.yaml, package/endpoint/data_stream/alerts/fields/fields.yml, package/endpoint/data_stream/file/fields/fields.yml, package/endpoint/data_stream/file/sample_event.json, package/endpoint/data_stream/library/fields/fields.yml, package/endpoint/data_stream/library/sample_event.json, package/endpoint/data_stream/process/fields/fields.yml, package/endpoint/data_stream/process/sample_event.json, package/endpoint/docs/README.md, schemas/v1/alerts/malware_event.yaml, schemas/v1/alerts/memory_protection_event.yaml, schemas/v1/alerts/ransomware_event.yaml, schemas/v1/alerts/rule_detection_event.yaml, schemas/v1/file/file.yaml, schemas/v1/library/library.yaml, schemas/v1/process/process.yaml
=> [backport][8.4] Volume device type (#276)

custom_subsets/elastic_endpoint/alerts/malware_event.yaml, custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml, custom_subsets/elastic_endpoint/alerts/ransomware_event.yaml, custom_subsets/elastic_endpoint/alerts/rule_detection_event.yaml, package/endpoint/data_stream/alerts/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/alerts/malware_event.yaml, schemas/v1/alerts/memory_protection_event.yaml, schemas/v1/alerts/ransomware_event.yaml, schemas/v1/alerts/rule_detection_event.yaml
=> [backport][8.4] replace file.Ext.* with existing fields within alerts (#281)

package/endpoint/changelog.yml
add changelog entries for the PRs that were backported to 8.4, slated for the 8.4.1 release (this PR will also be backported to there)
=> add changelog for 8.4.1

package/endpoint/changelog.yml
=> [backport][8.4] add changelog for 8.4.1 (#286)

package/endpoint/manifest.yml
bump kibana requirement to 8.5 stack for next release on the main branch
8.5
=> Bump kibana min for next cycle

.ci/jobs/endpoint-package-mbp.yml
Use boolean rather than strings.
=> jjbb: cosmetic change

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Updates changelog and sets package version to a production release
=> Update changelog and release num for 8.5

Makefile, package/endpoint/data_stream/alerts/fields/fields.yml, package/endpoint/data_stream/file/fields/fields.yml, package/endpoint/data_stream/library/fields/fields.yml, package/endpoint/data_stream/metadata/fields/fields.yml, package/endpoint/data_stream/metrics/fields/fields.yml, package/endpoint/data_stream/network/fields/fields.yml, package/endpoint/data_stream/policy/fields/fields.yml, package/endpoint/data_stream/process/fields/fields.yml, package/endpoint/data_stream/process/sample_event.json, package/endpoint/data_stream/registry/fields/fields.yml, package/endpoint/data_stream/security/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/alerts/linux_event_model_event.yaml, schemas/v1/alerts/malware_event.yaml, schemas/v1/alerts/memory_protection_event.yaml, schemas/v1/alerts/ransomware_event.yaml, schemas/v1/alerts/rule_detection_event.yaml, schemas/v1/file/file.yaml, schemas/v1/file/unquarantine.yaml, schemas/v1/library/library.yaml, schemas/v1/metadata/metadata.yaml, schemas/v1/metrics/metrics.yaml, schemas/v1/network/network.yaml, schemas/v1/policy/policy.yaml, schemas/v1/process/linux_event_model_event.yaml, schemas/v1/process/process.yaml, schemas/v1/registry/registry.yaml, schemas/v1/security/security.yaml
backports https://github.com/elastic/endpoint-package/pull/322 to 8.6
=> [8.6][backport] Update ECS to 8.5.2 (#322)

package/endpoint/changelog.yml
Update changelog in preparation for the 8.6.1 package release
=> Update changelog in preparation for 8.6.1

package/endpoint/changelog.yml, package/endpoint/manifest.yml
=> 8.6.1 release

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Added changelog entries and set release version
=> 8.7 Release

package/endpoint/manifest.yml
this preps the `8.7` branch to be in "prerelease" mode for any changes merged in, for the next release, which would be `8.7.1`
=> setup 8.7 minor series dev cycle

package/endpoint/manifest.yml
This preps the main branch to start the `8.8.0` dev cycle now that `8.7.0` has been released, and the `8.7` series branch has been cut
=> setup 8.8 dev cycle

doc_templates/endpoint/docs/README.md, package/endpoint/docs/README.md
Update the package overview description to add more detail.
Kibana: 8.7.0
Package: 8.7.1
~~- [ ] If these field(s) are "exception"-able, I made a companion PR to Kibana adding it (see [Readme](https://github.com/elastic/endpoint-package#exceptionable))~~
~~- [ ] If this is a `metadata` change, I also updated both transform destination schemas to match~~
~~- [ ] The new transform successfully starts in Kibana~~
~~- [ ] The corresponding transform destination schema was updated if necessary~~
=> Update package overview

custom_schemas/custom_api.yml, package/endpoint/data_stream/api/fields/fields.yml, schemas/v1/api/api.yaml
backports https://github.com/elastic/endpoint-package/pull/345 to 8.7
=> [8.7][backport][Fix] Make `process.Ext.api.name` indexable (#345)

doc_templates/endpoint/docs/README.md, package/endpoint/docs/README.md
backports https://github.com/elastic/endpoint-package/pull/346 to 8.7
=> [8.7][backport]Update package overview (#346)

package/endpoint/changelog.yml
Update changelog in preparation for the 8.7.1 package release
=> Update changelog in preparation for 8.7.1

package/endpoint/changelog.yml, package/endpoint/manifest.yml
=> 8.7.1 release

package/endpoint/changelog.yml
Changelog for upcoming release
8.8.0
=> Add changelog for 8.8.0

package/endpoint/manifest.yml
=> Release 8.8.0

package/endpoint/changelog.yml
Changelog updates for 8.9 release
=> 8.9 changelog

package/endpoint/manifest.yml
Release Endpoint package.  Should be merged after the changelog merges: https://github.com/elastic/endpoint-package/pull/374
=> Release 8.9 Endpoint package

package/endpoint/manifest.yml
=> Setup 8.9.1 cycle

package/endpoint/manifest.yml
=> Setup 8.10.0 cycle

doc_templates/endpoint/docs/README.md, package/endpoint/docs/README.md
Update description copy to:
`
Elastic Defend provides organizations with prevention, detection, and response capabilities with deep visibility for EPP, EDR, SIEM, and Security Analytics use cases across Windows, macOS, and Linux operating systems running on both traditional endpoints and public cloud environments. ​​Use Elastic Defend to:
`
Package copy in Kibana:
=> [Security Solution] Update description copy

package/endpoint/changelog.yml
=> [Security Solution] 8.9.1 changelog

package/endpoint/changelog.yml
Add 8.9.1 changelog
Backport of PR: https://github.com/elastic/endpoint-package/pull/383
=> [Security Solution] 8.9.1 changelog (#383)

package/endpoint/manifest.yml
8.9.1 release
Merge after changelog update: https://github.com/elastic/endpoint-package/pull/384
=> 8.9.1 release

.ci/Jenkinsfile
Setup Jenkins to publish from 8.9 branch
=> Setup Jenkins to publish from 8.9 branch

package/endpoint/manifest.yml
=> Setup 8.9.2 release

package/endpoint/changelog.yml
=> add 8.10 changelog entries

package/endpoint/manifest.yml
Performs the 8.10.0 release
(to be merged after #403)
=> 8.10.0 Release

.ci/Jenkinsfile, package/endpoint/changelog.yml, package/endpoint/elasticsearch/transform/metadata_current/transform.yml, package/endpoint/elasticsearch/transform/metadata_united/transform.yml
=> [backport][8.10] Revert unattended transforms (#407)

package/endpoint/changelog.yml, package/endpoint/manifest.yml
=> setup 8.10.2 dev cycle

package/endpoint/changelog.yml
=> update 8.10.2 changelog

package/endpoint/changelog.yml
=> [backport][8.10] update 8.10.2 changelog (#413)

package/endpoint/manifest.yml
=> Release 8.10.2

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Set up next dev cycle for 8.10 series
=> set up 8.10.3 dev cycle

custom_documentation/endpoint/data_stream/alerts/windows/windows_malware_alert.yaml, custom_documentation/endpoint/data_stream/metadata/metadata.yaml, custom_documentation/endpoint/data_stream/metrics/metrics.yaml, custom_documentation/endpoint/data_stream/policy/policy_response.yaml, package/endpoint/docs/custom_documentation/alerts/windows/windows_malware_alert.md, package/endpoint/docs/custom_documentation/metadata/metadata.md, package/endpoint/docs/custom_documentation/metrics/metrics.md, package/endpoint/docs/custom_documentation/policy/policy_response.md
Updated Endpoint custom documentation for 8.10 additions.
N/A
N/A
Just merging to main
Internal Endpoint tests pass and endpoint-package tests pass.
N/A
N/A
=> Custom documentation 8.10

custom_documentation/doc/endpoint/file/macos/macos_file_delete.md, custom_documentation/doc/endpoint/file/macos/macos_file_extended_attributes_delete.md, custom_documentation/doc/endpoint/file/macos/macos_file_launch_daemon.md, custom_documentation/doc/endpoint/file/macos/macos_file_modification.md, custom_documentation/doc/endpoint/file/macos/macos_file_mount.md, custom_documentation/doc/endpoint/file/macos/macos_file_rename.md, custom_documentation/src/endpoint/data_stream/file/macos/macos_file_delete.yaml, custom_documentation/src/endpoint/data_stream/file/macos/macos_file_extended_attributes_delete.yaml, custom_documentation/src/endpoint/data_stream/file/macos/macos_file_launch_daemon.yaml, custom_documentation/src/endpoint/data_stream/file/macos/macos_file_modification.yaml, custom_documentation/src/endpoint/data_stream/file/macos/macos_file_mount.yaml, custom_documentation/src/endpoint/data_stream/file/macos/macos_file_rename.yaml
Add Effective_process field to 8.10 custom documentation for Endpoint
=> [macOS] Add Effective_process fields for file events

.buildkite/pipeline.yml.py, .buildkite/scripts/build.sh, .buildkite/scripts/check.sh, .buildkite/scripts/find_oldest_supported_version.py, Makefile, catalog-info.yaml
This PR adds a dev pipeline that does following:
Here's a run of this pipeline: https://buildkite.com/elastic/endpoint-package/builds/36
Github status does not block any PR yet. This can be enabled later.
I am leaning toward creating a separated PR for publishing `main` or other releasable branches, and will not integrate this using pr-bot.
```json
```
=> Add buildkite Build step

package/endpoint/changelog.yml, package/endpoint/manifest.yml
prepare the 8.11 branch for next dev cycle
=> setup 8.11 dev cycle

package/endpoint/changelog.yml, package/endpoint/manifest.yml
prepare main branch for next release, now that 8.11 branch was cut
=> convert main branch to 8.12 release cycle

package/endpoint/manifest.yml
Bumps the prerelease number to force a (prerelease only) deployment of main branch
=> Bump 8.12 prerelease

package/endpoint/manifest.yml
=> validating publishing

.buildkite/pipeline.yml.py, .buildkite/scripts/build_info.py, .buildkite/scripts/find_oldest_supported_version.py, .buildkite/scripts/sign_and_publish.sh, .buildkite/sign_and_publish.yml.py, .ci/Jenkinsfile, catalog-info.yaml
backports all the buildkite commits to `8.12` branch
=> [8.12] Backport Buildkite

package/endpoint/manifest.yml
setup dev cycle for any patch-release work needed for 8.12 series
=> bump for any future patch-release work

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Changes for cutting 8.13 package release
=> Cut 8.13 release

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Setting up the dev cycle for any backports to 8.13 release
=> setup dev cycle for any patch releases for this series

catalog-info.yaml
=> [8.13][backport] add latest release branch to missed buildkite configs (#482)

custom_documentation/doc/endpoint/volume_device/windows/windows_volume_device_mount.md, custom_documentation/doc/endpoint/volume_device/windows/windows_volume_device_unmount.md
#470 missed committing these two files
=> add the files missing from #470

custom_subsets/elastic_endpoint/file/file.yaml, custom_subsets/elastic_endpoint/library/library.yaml, custom_subsets/elastic_endpoint/process/process.yaml, custom_subsets/elastic_endpoint/registry/registry.yaml, package/endpoint/data_stream/file/fields/fields.yml, package/endpoint/data_stream/file/sample_event.json, package/endpoint/data_stream/library/fields/fields.yml, package/endpoint/data_stream/library/sample_event.json, package/endpoint/data_stream/process/fields/fields.yml, package/endpoint/data_stream/process/sample_event.json, package/endpoint/data_stream/registry/fields/fields.yml, package/endpoint/data_stream/registry/sample_event.json, package/endpoint/docs/README.md, schemas/v1/file/file.yaml, schemas/v1/library/library.yaml, schemas/v1/process/process.yaml, schemas/v1/registry/registry.yaml
Add `process.thread.Ext.hardware_breakpoint_set` and `process.parent.thread.Ext.hardware_breakpoint_set`.
See `package/endpoint/data_stream/*/sample_event.json` changes.
8.14.0
=> HWBP => Production

catalog-info.yaml, package/endpoint/changelog.yml, package/endpoint/manifest.yml
- sets version in the manifest (the ultimate "current version" determining release process)
- updates the changelog for this release
- updates the branches for buildkite rules
=> Release 8.14

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Set up 8.14 branch for any point-release work
=> set up 8.14 ongoing dev cycle

package/endpoint/data_stream/security/fields/fields.yml, package/endpoint/docs/README.md
just a clean `make` to iron out any diffs from ecs build tooling.
CI will probably continue to fail on its `make` step unless it agrees with the field order here
this will be backported to `8.14` branch to fix any CI failures, but doesn't require a release
=> Fix formatting/order from ecs build tool

package/endpoint/data_stream/security/fields/fields.yml, package/endpoint/docs/README.md
=> [8.14][backport] fix formatting/order from ecs build tool (#505)

custom_documentation/doc/endpoint/alerts/windows/windows_malware_alert.md, custom_documentation/doc/endpoint/metrics/metrics.md, custom_documentation/doc/endpoint/network/linux/linux_network_connection_accepted.md, custom_documentation/doc/endpoint/network/linux/linux_network_connection_attempt.md, custom_documentation/doc/endpoint/process/macos/macos_process_exec.md, custom_documentation/doc/endpoint/process/macos/macos_process_exit.md, custom_documentation/doc/endpoint/process/macos/macos_process_remote_thread.md, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malware_alert.yaml, custom_documentation/src/endpoint/data_stream/file/windows/windows_file_open.yaml, custom_documentation/src/endpoint/data_stream/metrics/metrics.yaml, custom_documentation/src/endpoint/data_stream/network/linux/linux_network_connection_accepted.yaml, custom_documentation/src/endpoint/data_stream/network/linux/linux_network_connection_attempt.yaml, custom_documentation/src/endpoint/data_stream/process/macos/macos_process_exec.yaml, custom_documentation/src/endpoint/data_stream/process/macos/macos_process_exit.yaml, custom_documentation/src/endpoint/data_stream/process/macos/macos_process_remote_thread.yaml
=> 8.15 update custom documentation

catalog-info.yaml, package/endpoint/changelog.yml, package/endpoint/manifest.yml
8.15 Release PR
( [Previous Release PR](https://github.com/elastic/endpoint-package/pull/493) for reference)
=> Prepare 8.15 release

package/endpoint/changelog.yml, package/endpoint/manifest.yml
setup release branch `8.15` for any dev work or backport things for the next patch release
=> Prepare 8.15 dev cycle

package/endpoint/changelog.yml, package/endpoint/manifest.yml
setup `main` branch for next release version now that `8.15` branch has been cut
=> Prepare 8.16 dev cycle

package/endpoint/manifest.yml
bump to 8.16.0-prerelease.1
includes:
- #520
- #523
=> Bump prerelease

custom_documentation/doc/endpoint/library/windows/windows_library_load.md, custom_documentation/src/endpoint/data_stream/library/windows/windows_library_load.yaml, custom_subsets/elastic_endpoint/library/library.yaml, package/endpoint/data_stream/library/fields/fields.yml, package/endpoint/data_stream/library/sample_event.json, package/endpoint/data_stream/process/sample_event.json, package/endpoint/docs/README.md, schemas/v1/library/library.yaml
=> [backport] Add process.Ext.protection to Windows library events (#528)

package/endpoint/changelog.yml, package/endpoint/manifest.yml
only one change going in since `8.15.0`, so small changelog.
=> Release 8.15.1

custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malware_alert.yaml, custom_documentation/src/endpoint/data_stream/security/windows/windows_security_log_off.yaml, custom_documentation/src/endpoint/data_stream/security/windows/windows_security_log_on.yaml
Update custom documentation. The update was generated automatically from documents produced during EAF run, nothing to review really.
=> update custom documentation

custom_documentation/doc/endpoint/alerts/linux/linux_malware_alert.md, custom_documentation/doc/endpoint/alerts/macos/macos_malware_alert.md, custom_documentation/src/endpoint/data_stream/alerts/linux/linux_malware_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/macos/macos_malware_alert.yaml, custom_schemas/custom_malware_signature.yml, package/endpoint/data_stream/api/fields/fields.yml, schemas/v1/api/api.yaml
Backport https://github.com/elastic/endpoint-package/pull/538 to 8.15.
=> [8.15] [BACKPORT] Secondary Malware Signature Fields (#538)

catalog-info.yaml, package/endpoint/changelog.yml, package/endpoint/manifest.yml
8.16.0 Release PR
([previous release PR](https://github.com/elastic/endpoint-package/pull/515) for reference)
=> 8.16.0 Release

.buildkite/scripts/check.sh, package/endpoint/changelog.yml, package/endpoint/manifest.yml
This releases probably the final minor version for the 8.15 series, which contains #538 which was not yet released
=> Release 8.15.2

package/endpoint/changelog.yml, package/endpoint/manifest.yml
This is to be merged AFTER #557 
(previous [dev-cycle setup PR](https://github.com/elastic/endpoint-package/pull/517) for context)
=> Prepare 8.17 dev cycle on main branch

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Sets `8.15` branch back to dev-cycle mode after #559 is merged
=> Prep 8.15 for dev mode

catalog-info.yaml, package/endpoint/changelog.yml, package/endpoint/manifest.yml
Release 8.17 package
previous release PR for reference: #557
=> 8.17.0 Release

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Set up main branch for next release series
previous setup PR for context: #558
=> Prepare 8.18 dev cycle

custom_schemas/custom_process.yml, package/endpoint/data_stream/process/fields/fields.yml, package/endpoint/docs/README.md, package/endpoint/manifest.yml, schemas/v1/process/process.yaml
Correct a typo in some field types added in #564
8.18
=> Memfd field types fix

custom_documentation/doc/endpoint/network/linux/linux_network_dns_lookup_result.md, custom_documentation/src/endpoint/data_stream/network/linux/linux_network_dns_lookup_result.yaml
Add documentation or Linux DNS event.
8.18 or 8.19
=> Add linux dns events

custom_documentation/doc/endpoint/alerts/linux/linux_malicious_behavior_alert.md, custom_documentation/doc/endpoint/alerts/linux/linux_malware_alert.md, custom_documentation/doc/endpoint/alerts/linux/linux_memory_threat_alert.md, custom_documentation/doc/endpoint/alerts/macos/macos_malicious_behavior_alert.md, custom_documentation/doc/endpoint/alerts/macos/macos_malware_alert.md, custom_documentation/doc/endpoint/alerts/macos/macos_memory_threat_alert.md, custom_documentation/doc/endpoint/alerts/windows/windows_malicious_behavior_alert.md, custom_documentation/doc/endpoint/alerts/windows/windows_malware_alert.md, custom_documentation/doc/endpoint/alerts/windows/windows_memory_threat_alert.md, custom_documentation/doc/endpoint/alerts/windows/windows_ransomware_alert.md, custom_documentation/doc/endpoint/alerts/windows/windows_shellcode_thread.md, custom_documentation/doc/endpoint/api/windows/windows_api_tcpip.md, custom_documentation/src/endpoint/data_stream/alerts/linux/linux_malicious_behavior_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/linux/linux_malware_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/linux/linux_memory_threat_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/macos/macos_malicious_behavior_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/macos/macos_malware_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/macos/macos_memory_threat_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malicious_behavior_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malware_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_memory_threat_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_ransomware_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_shellcode_thread.yaml, custom_documentation/src/endpoint/data_stream/api/windows/windows_api_tcpip.yaml, schemas/v1/alerts/malware_event.yaml, schemas/v1/alerts/memory_protection_event.yaml, schemas/v1/alerts/ransomware_event.yaml
continuation of
* https://github.com/elastic/endpoint-package/pull/570
=> documentation update, policy name in alert

custom_documentation/doc/endpoint/metrics/metrics.md, custom_documentation/src/endpoint/data_stream/metrics/metrics.yaml
- add `Endpoint.metrics.system_impact.kernel_api_events` to custom documentation
8.18
=> update metrics custom documentation

custom_documentation/doc/endpoint/alerts/windows/windows_shellcode_thread.md, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_shellcode_thread.yaml
* add `Memory_protection.unique_key_v2` to custom documentation
8.18
=> update alerts custom documentation

catalog-info.yaml, package/endpoint/changelog.yml, package/endpoint/manifest.yml
8.18.0 Release PR
(A previous release PR for reference: #557 )
=> Release 8.18

package/endpoint/changelog.yml, package/endpoint/manifest.yml
Prep the `8.x` branch for the next development cycle
=> prep 8.19 series

.buildkite/pipeline.yml.py, .buildkite/sign_and_publish.yml.py, .ci/Jenkinsfile, catalog-info.yaml, package/endpoint/changelog.yml, package/endpoint/manifest.yml
Release PR for version `9.0.0`
(a [previous release PR](https://github.com/elastic/endpoint-package/pull/557) for reference)
some release regexes were updated as well to reflect the new major version number
=> 9.0 release

custom_schemas/custom_memory_region.yml, custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml, package/endpoint/data_stream/alerts/fields/fields.yml, package/endpoint/data_stream/alerts/sample_event.json, package/endpoint/data_stream/api/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/alerts/memory_protection_event.yaml, schemas/v1/api/api.yaml
Backports #591 to `8.x` branch
8.18
=> [backport][8.x] Change the size of region_start_bytes + add the field to the alert data stream

custom_schemas/custom_memory_region.yml, custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml, package/endpoint/data_stream/alerts/fields/fields.yml, package/endpoint/data_stream/alerts/sample_event.json, package/endpoint/data_stream/api/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/alerts/memory_protection_event.yaml, schemas/v1/api/api.yaml
Backports #591 to `8.18` series release
=> [backport][8.18] Change the size of region_start_bytes + add the field to the alert data stream

package/endpoint/changelog.yml
updates main branch changelog for the last two patch releases of #591
=> add changelogs for last patch releases to main

custom_documentation/doc/endpoint/process/macos/macos_process_already_running.md, custom_documentation/doc/endpoint/process/macos/macos_process_fork_exec_exit.md, custom_documentation/doc/endpoint/process/macos/macos_process_remote_thread.md, custom_documentation/src/endpoint/data_stream/process/macos/macos_process_already_running.yaml, custom_documentation/src/endpoint/data_stream/process/macos/macos_process_fork_exec_exit.yaml, custom_documentation/src/endpoint/data_stream/process/macos/macos_process_remote_thread.yaml
Adds custom documentation fields for parent.command_line for macos process events
=> update macos process events to include parent.command_line

.buildkite/scripts/check.sh, doc_templates/endpoint/docs/README.md, package/endpoint/docs/README.md
=> [8.18] Backport rules notice

.buildkite/scripts/check.sh, doc_templates/endpoint/docs/README.md, package/endpoint/docs/README.md, package/endpoint/manifest.yml
=> [8.17] Backport rules notice

.buildkite/scripts/check.sh, doc_templates/endpoint/docs/README.md, package/endpoint/docs/README.md, package/endpoint/manifest.yml
=> [8.16] Backport rules notice

package/endpoint/manifest.yml
Bumps prerelease version, to preview dev features
=> Bump 9.1 prerelease

.buildkite/sign_and_publish.yml.py
=> [backport][8.16] disable DRY_RUN on releasable branches (#589)

.buildkite/sign_and_publish.yml.py
=> [backport][8.17] disable DRY_RUN on releasable branches (#589)

custom_documentation/doc/endpoint/alerts/linux/linux_malicious_behavior_alert.md, custom_documentation/doc/endpoint/alerts/linux/linux_memory_threat_alert.md, custom_documentation/doc/endpoint/alerts/macos/macos_malicious_behavior_alert.md, custom_documentation/doc/endpoint/alerts/macos/macos_memory_threat_alert.md, custom_documentation/doc/endpoint/alerts/windows/windows_malicious_behavior_alert.md, custom_documentation/doc/endpoint/alerts/windows/windows_memory_threat_alert.md, custom_documentation/doc/endpoint/alerts/windows/windows_ransomware_alert.md, custom_documentation/src/endpoint/data_stream/alerts/linux/linux_malicious_behavior_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/linux/linux_memory_threat_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/macos/macos_malicious_behavior_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/macos/macos_memory_threat_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malicious_behavior_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_memory_threat_alert.yaml, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_ransomware_alert.yaml
- Related https://github.com/elastic/endpoint-package/pull/632
Update custom documentation only.
=> global artifacts manifest_type, fix custom documentation

package/endpoint/manifest.yml
=> Release 9.1.0

custom_documentation/doc/endpoint/alerts/windows/windows_malicious_behavior_alert.md, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malicious_behavior_alert.yaml, custom_subsets/elastic_endpoint/alerts/rule_detection_event.yaml, package/endpoint/data_stream/alerts/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/alerts/rule_detection_event.yaml
=> [backport][8.19] add destination.domain as part of the alert (#650)

custom_documentation/doc/endpoint/alerts/windows/windows_malicious_behavior_alert.md, custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malicious_behavior_alert.yaml, custom_subsets/elastic_endpoint/alerts/rule_detection_event.yaml, package/endpoint/data_stream/alerts/fields/fields.yml, package/endpoint/docs/README.md, schemas/v1/alerts/rule_detection_event.yaml
=> [backport][9.1] add destination.domain as part of the alert (#650)
